import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const runtimeFile = path.join(root, "plugin", "runtime", "promptgauge.cjs");

export async function buildPluginRuntime() {
  fs.mkdirSync(path.dirname(runtimeFile), { recursive: true });
  await esbuild.build({
    absWorkingDir: root,
    entryPoints: [path.join(root, "src", "index.ts")],
    outfile: runtimeFile,
    bundle: true,
    platform: "node",
    format: "cjs",
    target: "node22",
    legalComments: "none",
    logLevel: "silent",
    banner: {
      js: "/** Generated by scripts/build-plugin.mjs. Do not edit. Source of truth: src/ */",
    },
  });
}

export function validatePlugin() {
  const errors = [];
  const packageJson = readJson(path.join(root, "package.json"));
  const pluginJson = readJson(path.join(root, "plugin", ".claude-plugin", "plugin.json"));
  const marketplace = readJson(path.join(root, ".claude-plugin", "marketplace.json"));
  const hooks = readJson(path.join(root, "plugin", "hooks", "hooks.json"));
  const versionFile = fs.readFileSync(path.join(root, "src", "version.ts"), "utf8");
  const versionMatch = versionFile.match(/VERSION = "([^"]+)"/);
  const sourceVersion = versionMatch?.[1];

  if (!packageJson.version) {
    errors.push("package.json is missing version");
  }
  if (pluginJson.version !== packageJson.version) {
    errors.push(
      `plugin.json version ${pluginJson.version} does not match package.json ${packageJson.version}`,
    );
  }
  if (sourceVersion !== packageJson.version) {
    errors.push(
      `src/version.ts ${sourceVersion} does not match package.json ${packageJson.version}`,
    );
  }
  if (marketplace.name !== "promptgauge") {
    errors.push("marketplace name must be promptgauge");
  }
  if (marketplace.plugins?.[0]?.source !== "./plugin") {
    errors.push("marketplace plugin source must be ./plugin");
  }
  if (marketplace.plugins?.[0]?.name !== "promptgauge") {
    errors.push("marketplace plugin name must be promptgauge");
  }
  if (marketplace.plugins?.[0]?.version !== packageJson.version) {
    errors.push(
      `marketplace plugin version ${marketplace.plugins?.[0]?.version} does not match package.json ${packageJson.version}`,
    );
  }
  if (!pluginJson.name || !pluginJson.displayName || !pluginJson.description) {
    errors.push("plugin.json is missing required metadata");
  }
  if (!fs.existsSync(runtimeFile)) {
    errors.push("plugin runtime is missing; run the plugin build");
  }
  const hookCommand = hooks.hooks?.UserPromptSubmit?.[0]?.hooks?.[0]?.command ?? "";
  if (!hookCommand.includes("${CLAUDE_PLUGIN_ROOT}/runtime/promptgauge.cjs")) {
    errors.push("plugin hooks must call the bundled runtime via CLAUDE_PLUGIN_ROOT");
  }
  if (!hookCommand.includes('"${CLAUDE_PLUGIN_ROOT}/runtime/promptgauge.cjs"')) {
    errors.push("plugin hook command must quote the runtime path");
  }
  if (hookCommand.includes("\\")) {
    errors.push("plugin hook command must use forward slashes");
  }
  for (const skill of ["setup", "status", "doctor", "uninstall"]) {
    const skillFile = path.join(root, "plugin", "skills", skill, "SKILL.md");
    if (!fs.existsSync(skillFile)) {
      errors.push(`missing skill ${skill}`);
    }
  }
  if (!fs.existsSync(path.join(root, "plugin", "bin", "promptgauge"))) {
    errors.push("missing plugin/bin/promptgauge");
  }
  return { ok: errors.length === 0, errors, version: packageJson.version };
}

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const result = await buildPluginRuntime();
  void result;
  const validation = validatePlugin();
  if (!validation.ok) {
    console.error(validation.errors.join("\n"));
    process.exit(1);
  }
  console.log(`plugin ${validation.version} ready`);
}
