#!/usr/bin/env node
/** Generated by scripts/build-plugin.mjs. Do not edit. Source of truth: src/ */
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// src/utils/cli-entry.ts
var import_node_path = __toESM(require("node:path"), 1);
function resolveCliEntry(explicit) {
  if (explicit && explicit.length > 0) {
    return import_node_path.default.resolve(explicit);
  }
  const argv1 = process.argv[1];
  if (argv1 && argv1.length > 0) {
    return import_node_path.default.resolve(argv1);
  }
  return import_node_path.default.resolve(".");
}

// src/version.ts
var VERSION = "0.4.0";
var DISPLAY_NAME = "PromptGauge";
var DEFAULT_DATA_DIR_NAME = ".promptgauge";
var EVENTS_FILE_NAME = "events.jsonl";
var CONFIG_FILE_NAME = "config.json";
var STATUSLINE_STATE_FILE_NAME = "statusline-state.json";
var HOOKS_STATE_FILE_NAME = "hooks-state.json";
var WRAPPER_MARKER = "--pg-wrapper";
var HOOK_MARKER = "--pg-hook";

// src/core/config/load.ts
var import_node_fs = __toESM(require("node:fs"), 1);
var import_node_path2 = __toESM(require("node:path"), 1);

// src/utils/json.ts
function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function asString(value) {
  return typeof value === "string" && value.length > 0 ? value : void 0;
}
function asFiniteNumber(value) {
  return typeof value === "number" && Number.isFinite(value) ? value : void 0;
}
function asBoolean(value) {
  return typeof value === "boolean" ? value : void 0;
}
function parseJson(text) {
  try {
    return { ok: true, value: JSON.parse(text) };
  } catch {
    return { ok: false, error: "malformed JSON" };
  }
}

// src/core/config/model.ts
var DEFAULT_CONFIG = {
  mode: "observe",
  thresholds: {
    warning: 70,
    critical: 85,
    emergency: 95
  },
  privacy: {
    storePromptText: false
  },
  freshnessMs: 15 * 60 * 1e3
};
function normalizeConfig(input) {
  const warnings = [];
  const raw = isObject(input) ? input : {};
  const mode = raw.mode === "enforce" ? "observe" : raw.mode === "observe" ? "observe" : "observe";
  if (raw.mode === "enforce") {
    warnings.push("mode=enforce is not supported in this pre-release; observe-only is used.");
  }
  const thresholdsRaw = isObject(raw.thresholds) ? raw.thresholds : {};
  let warning = asPercent(thresholdsRaw.warning, DEFAULT_CONFIG.thresholds.warning);
  let critical = asPercent(thresholdsRaw.critical, DEFAULT_CONFIG.thresholds.critical);
  let emergency = asPercent(thresholdsRaw.emergency, DEFAULT_CONFIG.thresholds.emergency);
  if (!(warning < critical && critical < emergency)) {
    warnings.push("invalid thresholds; using defaults 70/85/95.");
    warning = DEFAULT_CONFIG.thresholds.warning;
    critical = DEFAULT_CONFIG.thresholds.critical;
    emergency = DEFAULT_CONFIG.thresholds.emergency;
  }
  const privacyRaw = isObject(raw.privacy) ? raw.privacy : {};
  if (privacyRaw.storePromptText === true) {
    warnings.push("privacy.storePromptText is unsupported in V1 and remains false.");
  }
  const freshnessMs = typeof raw.freshnessMs === "number" && Number.isFinite(raw.freshnessMs) && raw.freshnessMs > 0 ? raw.freshnessMs : DEFAULT_CONFIG.freshnessMs;
  return {
    config: {
      mode,
      thresholds: { warning, critical, emergency },
      privacy: { storePromptText: false },
      freshnessMs
    },
    warnings
  };
}
function isObject(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function asPercent(value, fallback) {
  return typeof value === "number" && Number.isFinite(value) && value >= 0 && value <= 100 ? value : fallback;
}

// src/core/config/load.ts
function loadConfig(dataDir) {
  const filePath = import_node_path2.default.join(dataDir, CONFIG_FILE_NAME);
  if (!import_node_fs.default.existsSync(filePath)) {
    return { config: DEFAULT_CONFIG, warnings: [], path: filePath, existed: false };
  }
  const text = import_node_fs.default.readFileSync(filePath, "utf8");
  const parsed = parseJson(text);
  if (!parsed.ok) {
    return {
      config: DEFAULT_CONFIG,
      warnings: ["config.json is malformed; using defaults."],
      path: filePath,
      existed: true
    };
  }
  const normalized = normalizeConfig(parsed.value);
  return { ...normalized, path: filePath, existed: true };
}
function writeDefaultConfig(dataDir) {
  import_node_fs.default.mkdirSync(dataDir, { recursive: true });
  const filePath = import_node_path2.default.join(dataDir, CONFIG_FILE_NAME);
  if (!import_node_fs.default.existsSync(filePath)) {
    import_node_fs.default.writeFileSync(filePath, `${JSON.stringify(DEFAULT_CONFIG, null, 2)}
`, "utf8");
  }
  return filePath;
}

// src/utils/time.ts
var MS_MINUTE = 6e4;
var MS_HOUR = 60 * MS_MINUTE;
var MS_DAY = 24 * MS_HOUR;
function parseIso(value) {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? void 0 : date;
}
function epochSecondsToDate(epochSeconds) {
  return new Date(epochSeconds * 1e3);
}
function formatDurationUntil(target, now) {
  const delta = target.getTime() - now.getTime();
  if (delta <= 0) {
    return "elapsed";
  }
  return formatDuration(delta);
}
function formatDuration(ms) {
  const abs = Math.max(0, Math.floor(ms));
  const days = Math.floor(abs / MS_DAY);
  const hours = Math.floor(abs % MS_DAY / MS_HOUR);
  const minutes = Math.floor(abs % MS_HOUR / MS_MINUTE);
  if (days > 0) {
    return `${days}d ${pad2(hours)}h`;
  }
  return `${pad2(hours)}h ${pad2(minutes)}m`;
}
function pad2(value) {
  return value.toString().padStart(2, "0");
}
function isStale(capturedAt, now, maxAgeMs) {
  const captured = parseIso(capturedAt);
  if (!captured) {
    return true;
  }
  return now.getTime() - captured.getTime() > maxAgeMs;
}

// src/core/burn-detection/engine.ts
var DEFAULT_WINDOW_MS = 10 * 60 * 1e3;
function evaluateBurn(input) {
  const windowMs = input.windowMs ?? DEFAULT_WINDOW_MS;
  const recent = input.events.filter((event) => inWindow(event.capturedAt, input.now, windowMs));
  if (recent.length === 0) {
    return {
      level: "UNKNOWN",
      reason: "not enough recent activity to assess burn",
      signals: []
    };
  }
  const signals = [];
  const quotaSignal = quotaAcceleration(recent, windowMs);
  if (quotaSignal) {
    signals.push(quotaSignal);
  }
  const toolSignal = toolCallRate(recent, windowMs);
  if (toolSignal) {
    signals.push(toolSignal);
  }
  const subagentSignal = subagentRate(recent);
  if (subagentSignal) {
    signals.push(subagentSignal);
  }
  const repeatSignal = repeatedTools(recent);
  if (repeatSignal) {
    signals.push(repeatSignal);
  }
  if (signals.length === 0) {
    return {
      level: "NORMAL",
      reason: "no elevated burn signals in the recent window",
      signals
    };
  }
  const highCount = signals.filter((signal) => signal.level === "HIGH").length;
  const elevatedCount = signals.filter((signal) => signal.level === "ELEVATED").length;
  const hasQuotaHigh = signals.some(
    (signal) => signal.name === "quota_delta" && signal.level === "HIGH"
  );
  const hasActivityHigh = signals.some(
    (signal) => signal.name !== "quota_delta" && signal.level === "HIGH"
  );
  if (highCount >= 2 || hasQuotaHigh && hasActivityHigh) {
    return {
      level: "RUNAWAY",
      reason: `multiple strong signals: ${signals.map((s) => s.name).join(", ")}`,
      signals
    };
  }
  if (highCount === 1) {
    return {
      level: "HIGH",
      reason: signals.find((signal) => signal.level === "HIGH")?.reason ?? "high burn signal",
      signals
    };
  }
  if (elevatedCount >= 1) {
    return {
      level: "ELEVATED",
      reason: signals[0]?.reason ?? "elevated burn signal",
      signals
    };
  }
  return {
    level: "NORMAL",
    reason: "no elevated burn signals in the recent window",
    signals
  };
}
function inWindow(capturedAt, now, windowMs) {
  const date = parseIso(capturedAt);
  if (!date) {
    return false;
  }
  const delta = now.getTime() - date.getTime();
  return delta >= 0 && delta <= windowMs;
}
function quotaAcceleration(events, windowMs) {
  const snapshots = events.filter((event) => event.type === "quota_snapshot").map((event) => {
    if (event.type !== "quota_snapshot") {
      return void 0;
    }
    return {
      at: parseIso(event.capturedAt)?.getTime() ?? 0,
      used: event.fiveHour?.usedPercentage
    };
  }).filter(
    (row) => row !== void 0 && row.used !== void 0
  ).sort((a, b) => a.at - b.at);
  if (snapshots.length < 2) {
    return void 0;
  }
  const first = snapshots[0];
  const last = snapshots[snapshots.length - 1];
  const delta = last.used - first.used;
  if (delta < 10) {
    return void 0;
  }
  const spanMinutes = Math.max(1, (last.at - first.at) / 6e4);
  const perTenMin = delta / spanMinutes * (windowMs / 6e4);
  if (delta >= 30 || perTenMin >= 30) {
    return {
      name: "quota_delta",
      level: "HIGH",
      reason: `5-hour quota rose ${delta.toFixed(1)} points in ${spanMinutes.toFixed(1)}m`
    };
  }
  if (delta >= 15 || perTenMin >= 15) {
    return {
      name: "quota_delta",
      level: "ELEVATED",
      reason: `5-hour quota rose ${delta.toFixed(1)} points in ${spanMinutes.toFixed(1)}m`
    };
  }
  return void 0;
}
function toolCallRate(events, _windowMs) {
  const tools = events.filter((event) => event.type === "tool_activity" && event.phase === "pre");
  if (tools.length >= 60) {
    return {
      name: "tool_rate",
      level: "HIGH",
      reason: `${tools.length} tool calls observed in the recent window`
    };
  }
  if (tools.length >= 30) {
    return {
      name: "tool_rate",
      level: "ELEVATED",
      reason: `${tools.length} tool calls observed in the recent window`
    };
  }
  return void 0;
}
function subagentRate(events) {
  const starts = events.filter(
    (event) => event.type === "subagent_activity" && event.phase === "start"
  );
  if (starts.length >= 10) {
    return {
      name: "subagent_rate",
      level: "HIGH",
      reason: `${starts.length} subagents started in the recent window`
    };
  }
  if (starts.length >= 5) {
    return {
      name: "subagent_rate",
      level: "ELEVATED",
      reason: `${starts.length} subagents started in the recent window`
    };
  }
  return void 0;
}
function repeatedTools(events) {
  const counts = /* @__PURE__ */ new Map();
  for (const event of events) {
    if (event.type !== "tool_activity" || event.phase !== "pre" || !event.toolName) {
      continue;
    }
    counts.set(event.toolName, (counts.get(event.toolName) ?? 0) + 1);
  }
  let topName = "";
  let topCount = 0;
  for (const [name, count] of counts) {
    if (count > topCount) {
      topName = name;
      topCount = count;
    }
  }
  if (topCount >= 25) {
    return {
      name: "repeated_tool",
      level: "HIGH",
      reason: `${topName} invoked ${topCount} times in the recent window`
    };
  }
  if (topCount >= 15) {
    return {
      name: "repeated_tool",
      level: "ELEVATED",
      reason: `${topName} invoked ${topCount} times in the recent window`
    };
  }
  return void 0;
}

// src/core/circuit-breaker/engine.ts
var STATE_RANK = {
  UNKNOWN: 0,
  NORMAL: 1,
  WARNING: 2,
  CRITICAL: 3,
  EMERGENCY: 4
};
function evaluateCircuitBreaker(input) {
  const observeActionPrefix = input.mode === "enforce" ? "Enforcement is not enabled in this pre-release. " : "";
  if (!input.snapshot) {
    return unknown("no quota snapshot is available", observeActionPrefix);
  }
  if (isStale(input.snapshot.capturedAt, input.now, input.freshnessMs)) {
    return unknown("quota telemetry is stale", observeActionPrefix);
  }
  const five = windowState(input.snapshot.fiveHour?.value, input.now, input.thresholds, "5-hour");
  const seven = windowState(input.snapshot.sevenDay?.value, input.now, input.thresholds, "7-day");
  if (five.kind === "missing" && seven.kind === "missing") {
    return unknown("live subscription quota unavailable", observeActionPrefix);
  }
  const candidates = [five, seven].filter((item) => item.kind === "ok");
  if (candidates.length === 0) {
    const reset = [five, seven].find((item) => item.kind === "reset");
    return unknown(reset?.reason ?? "quota windows are past reset", observeActionPrefix);
  }
  let best = candidates[0];
  for (const candidate of candidates.slice(1)) {
    if (STATE_RANK[candidate.state] > STATE_RANK[best.state]) {
      best = candidate;
    }
  }
  return {
    state: best.state,
    reason: best.reason,
    recommendedAction: recommendedAction(best.state, observeActionPrefix),
    mode: "observe",
    governingWindow: best.window
  };
}
function unknown(reason, prefix) {
  return {
    state: "UNKNOWN",
    reason,
    recommendedAction: `${prefix}Do not treat missing quota data as safe. Check Claude Code status-line integration.`,
    mode: "observe"
  };
}
function recommendedAction(state, prefix) {
  switch (state) {
    case "NORMAL":
      return `${prefix}No action required. Continue observing.`;
    case "WARNING":
      return `${prefix}Review current Claude Code activity. This pre-release does not block sessions.`;
    case "CRITICAL":
      return `${prefix}Slow down autonomous work. This pre-release does not block sessions.`;
    case "EMERGENCY":
      return `${prefix}Consider stopping the session manually. This pre-release does not block sessions.`;
    case "UNKNOWN":
      return `${prefix}Do not treat unknown quota as safe.`;
  }
}
function windowState(window, now, thresholds, label) {
  if (!window) {
    return { kind: "missing" };
  }
  if (epochSecondsToDate(window.resetsAtEpochSeconds).getTime() <= now.getTime()) {
    return {
      kind: "reset",
      reason: `${label} snapshot is past its reset time`
    };
  }
  const used = window.usedPercentage;
  const key = label === "5-hour" ? "five_hour" : "seven_day";
  if (used >= thresholds.emergency) {
    return {
      kind: "ok",
      state: "EMERGENCY",
      reason: `${label} quota reported ${formatPct(used)}% used`,
      window: key
    };
  }
  if (used >= thresholds.critical) {
    return {
      kind: "ok",
      state: "CRITICAL",
      reason: `${label} quota reported ${formatPct(used)}% used`,
      window: key
    };
  }
  if (used >= thresholds.warning) {
    return {
      kind: "ok",
      state: "WARNING",
      reason: `${label} quota reported ${formatPct(used)}% used`,
      window: key
    };
  }
  return {
    kind: "ok",
    state: "NORMAL",
    reason: `${label} quota reported ${formatPct(used)}% used`,
    window: key
  };
}
function formatPct(value) {
  return Number.isInteger(value) ? String(value) : value.toFixed(1);
}

// src/core/quota/delta.ts
function quotaDelta(start, end, capturedAt) {
  if (!start || !end) {
    return void 0;
  }
  if (start.resetsAtEpochSeconds !== end.resetsAtEpochSeconds) {
    return void 0;
  }
  const capturedMs = Date.parse(capturedAt);
  if (Number.isFinite(capturedMs) && capturedMs >= end.resetsAtEpochSeconds * 1e3) {
    return void 0;
  }
  if (end.usedPercentage < start.usedPercentage) {
    return void 0;
  }
  return {
    value: end.usedPercentage - start.usedPercentage,
    source: "quota_snapshot_pair",
    capturedAt,
    provenance: "derived",
    confidence: "medium"
  };
}
function costDeltaUsd(startUsd, endUsd, capturedAt) {
  if (startUsd === void 0 || endUsd === void 0) {
    return void 0;
  }
  if (endUsd < startUsd) {
    return void 0;
  }
  return {
    value: endUsd - startUsd,
    source: "cost.total_cost_usd",
    capturedAt,
    provenance: "derived_from_claude_reported_session_cost",
    confidence: "medium"
  };
}
function snapshotsForPrompt(events, promptId) {
  return events.filter((event) => {
    return event.type === "quota_snapshot" && event.promptId === promptId;
  }).map(toSnapshot);
}
function toSnapshot(event) {
  return {
    capturedAt: event.capturedAt,
    source: "claude_statusline",
    provenance: "claude_reported",
    sessionId: event.sessionId,
    promptId: event.promptId,
    claudeVersion: event.claudeVersion,
    model: event.model,
    projectKey: event.projectKey,
    projectBasename: event.projectBasename,
    estimatedApiCostUsd: event.estimatedApiCostUsd === void 0 ? void 0 : {
      value: event.estimatedApiCostUsd,
      source: "cost.total_cost_usd",
      capturedAt: event.capturedAt,
      provenance: "claude_reported_estimate",
      confidence: "high"
    },
    contextWindow: event.contextWindow,
    fiveHour: event.fiveHour ? {
      value: event.fiveHour,
      source: "claude_statusline",
      capturedAt: event.capturedAt,
      provenance: "claude_reported",
      confidence: "high"
    } : void 0,
    sevenDay: event.sevenDay ? {
      value: event.sevenDay,
      source: "claude_statusline",
      capturedAt: event.capturedAt,
      provenance: "claude_reported",
      confidence: "high"
    } : void 0,
    spendLimit: event.spendLimit ? {
      value: event.spendLimit,
      source: "claude_statusline",
      capturedAt: event.capturedAt,
      provenance: "claude_reported",
      confidence: "high"
    } : void 0,
    promptCache: event.promptCache
  };
}

// src/core/attribution/correlate.ts
var SNAPSHOT_CORRELATION_WINDOW_MS = 15 * 60 * 1e3;
var START_SNAPSHOT_GRACE_MS = 5e3;
var END_SNAPSHOT_GRACE_MS = 3e4;
var CORRELATION_RULES = "nearest eligible snapshot; same session; same prompt_id when the snapshot has one; within 15m; start grace 5s; end grace 30s; same reset window for quota delta; snapshots are not treated as simultaneous with hooks";
function buildPromptUsageRecord(events, promptId) {
  const starts = events.filter(
    (event) => event.type === "prompt_lifecycle" && event.phase === "start" && event.promptId === promptId
  );
  const ends = events.filter(
    (event) => event.type === "prompt_lifecycle" && (event.phase === "stop" || event.phase === "stop_failure") && event.promptId === promptId
  );
  const start = starts[0];
  const end = ends[ends.length - 1];
  const sessionId = start?.sessionId ?? end?.sessionId;
  const startedAt = start?.capturedAt;
  const endedAt = end?.capturedAt;
  const durationMs = startedAt && endedAt ? Math.max(0, Date.parse(endedAt) - Date.parse(startedAt)) : void 0;
  const pair = start && end && start.sessionId && start.sessionId === end.sessionId ? correlateSnapshots(events, promptId, start.sessionId, startedAt, endedAt) : { before: void 0, after: void 0 };
  return {
    sessionId,
    promptId,
    startedAt,
    endedAt,
    durationMs: Number.isFinite(durationMs) ? durationMs : void 0,
    open: !end,
    fiveHour: bracketQuota(pair.before?.fiveHour, pair.after?.fiveHour, pair.after?.capturedAt),
    sevenDay: bracketQuota(pair.before?.sevenDay, pair.after?.sevenDay, pair.after?.capturedAt),
    spendLimit: bracketQuota(
      pair.before?.spendLimit,
      pair.after?.spendLimit,
      pair.after?.capturedAt
    ),
    estimatedSessionCostBefore: pair.before?.estimatedApiCostUsd,
    estimatedSessionCostAfter: pair.after?.estimatedApiCostUsd,
    estimatedSessionCostDelta: costDeltaUsd(
      pair.before?.estimatedApiCostUsd,
      pair.after?.estimatedApiCostUsd,
      pair.after?.capturedAt ?? endedAt ?? startedAt ?? ""
    ),
    exactPromptTokenConsumption: "unavailable",
    correlation: CORRELATION_RULES
  };
}
function correlateSnapshots(events, promptId, sessionId, startedAt, endedAt) {
  if (!startedAt) {
    return {};
  }
  const snapshots = events.filter(
    (event) => event.type === "quota_snapshot" && event.sessionId === sessionId
  );
  const startMs = Date.parse(startedAt);
  const endMs = endedAt ? Date.parse(endedAt) : Number.NaN;
  if (!Number.isFinite(startMs)) {
    return {};
  }
  const before = nearest(
    snapshots.filter((event) => isEligibleBefore(event, promptId, startMs)),
    startMs
  );
  if (!Number.isFinite(endMs)) {
    return { before };
  }
  const after = nearest(
    snapshots.filter((event) => isEligibleAfter(event, promptId, startMs, endMs)),
    endMs
  );
  return { before, after };
}
function isEligibleBefore(event, promptId, startMs) {
  const captured = Date.parse(event.capturedAt);
  if (!Number.isFinite(captured)) {
    return false;
  }
  if (captured > startMs + START_SNAPSHOT_GRACE_MS) {
    return false;
  }
  if (Math.abs(startMs - captured) > SNAPSHOT_CORRELATION_WINDOW_MS) {
    return false;
  }
  if (event.promptId && event.promptId === promptId && captured > startMs) {
    return false;
  }
  if (event.promptId === promptId && captured <= startMs) {
    return false;
  }
  return true;
}
function isEligibleAfter(event, promptId, startMs, endMs) {
  const captured = Date.parse(event.capturedAt);
  if (!Number.isFinite(captured)) {
    return false;
  }
  if (captured < startMs) {
    return false;
  }
  if (captured > endMs + END_SNAPSHOT_GRACE_MS) {
    return false;
  }
  if (Math.abs(endMs - captured) > SNAPSHOT_CORRELATION_WINDOW_MS) {
    return false;
  }
  if (event.promptId && event.promptId !== promptId) {
    return false;
  }
  return true;
}
function nearest(snapshots, targetMs) {
  let best;
  let bestDistance = Number.POSITIVE_INFINITY;
  for (const snapshot of snapshots) {
    const captured = Date.parse(snapshot.capturedAt);
    const distance = Math.abs(captured - targetMs);
    if (distance < bestDistance) {
      best = snapshot;
      bestDistance = distance;
    }
  }
  return best;
}
function bracketQuota(before, after, capturedAt) {
  if (!before && !after) {
    return void 0;
  }
  return {
    before,
    after,
    delta: capturedAt ? quotaDelta(before, after, capturedAt) : void 0
  };
}
function estimatedApiCostDeltaForPrompt(events, promptId) {
  return buildPromptUsageRecord(events, promptId).estimatedSessionCostDelta;
}

// src/core/attribution/prompt-lifecycle.ts
var LIMITATION = "Quota delta is not token consumption. Estimated API cost delta is derived from cost.total_cost_usd and is not subscription billing. Exact prompt token consumption is unavailable. Snapshots are correlated, not assumed simultaneous with hooks.";
function attributePrompt(events, promptId) {
  const related = events.filter((event) => "promptId" in event && event.promptId === promptId);
  const starts = related.filter(
    (event) => event.type === "prompt_lifecycle" && event.phase === "start"
  );
  const ends = related.filter(
    (event) => event.type === "prompt_lifecycle" && (event.phase === "stop" || event.phase === "stop_failure")
  );
  const start = starts[0];
  const end = ends[ends.length - 1];
  const snapshots = snapshotsForPrompt(events, promptId);
  const lastSnap = snapshots[snapshots.length - 1];
  const usage = buildPromptUsageRecord(events, promptId);
  return {
    promptId,
    sessionId: start && "sessionId" in start ? start.sessionId : lastSnap?.sessionId,
    startedAt: start?.capturedAt ?? usage.startedAt,
    endedAt: end?.capturedAt,
    open: !end,
    toolCallCount: related.filter(
      (event) => event.type === "tool_activity" && event.phase === "pre"
    ).length,
    subagentStartCount: related.filter(
      (event) => event.type === "subagent_activity" && event.phase === "start"
    ).length,
    taskCreatedCount: related.filter(
      (event) => event.type === "task_lifecycle" && event.phase === "created"
    ).length,
    quotaDeltaFiveHour: usage.fiveHour?.delta,
    quotaDeltaSevenDay: usage.sevenDay?.delta,
    estimatedApiCostDelta: estimatedApiCostDeltaForPrompt(events, promptId),
    latestContextWindow: lastSnap?.contextWindow,
    exactPromptTokenConsumption: "unavailable",
    limitation: LIMITATION,
    usage
  };
}
function promptsInSession(events, sessionId) {
  const ids = /* @__PURE__ */ new Set();
  for (const event of events) {
    if ("sessionId" in event && event.sessionId === sessionId && "promptId" in event && event.promptId) {
      ids.add(event.promptId);
    }
  }
  return [...ids];
}

// src/core/accounting/session-summary.ts
function summarizeSession(events) {
  const latestQuotaEvent = [...events].reverse().find((event) => event.type === "quota_snapshot");
  const latestAny = events[events.length - 1];
  const sessionId = (latestQuotaEvent && "sessionId" in latestQuotaEvent ? latestQuotaEvent.sessionId : void 0) ?? (latestAny && "sessionId" in latestAny ? latestAny.sessionId : void 0);
  const promptIds = sessionId ? promptsInSession(events, sessionId) : uniquePromptIds(events);
  const latestPromptId = latestPrompt(events, promptIds);
  return {
    sessionId,
    promptsObserved: promptIds.length,
    latestPrompt: latestPromptId ? attributePrompt(events, latestPromptId) : void 0,
    latestQuota: latestQuotaEvent ? toSnapshot(latestQuotaEvent) : void 0
  };
}
function uniquePromptIds(events) {
  const ids = /* @__PURE__ */ new Set();
  for (const event of events) {
    if ("promptId" in event && event.promptId) {
      ids.add(event.promptId);
    }
  }
  return [...ids];
}
function latestPrompt(events, promptIds) {
  for (let i = events.length - 1; i >= 0; i -= 1) {
    const event = events[i];
    if (event && "promptId" in event && event.promptId && promptIds.includes(event.promptId)) {
      return event.promptId;
    }
  }
  return promptIds[promptIds.length - 1];
}

// src/core/provenance.ts
function displayProvenance(provenance) {
  switch (provenance) {
    case "claude_reported":
      return "CLAUDE_REPORTED";
    case "claude_reported_estimate":
      return "CLAUDE_REPORTED_ESTIMATE";
    case "derived":
      return "DERIVED";
    case "derived_from_claude_reported_session_cost":
      return "DERIVED_FROM_CLAUDE_REPORTED_SESSION_COST";
    case "estimated":
      return "ESTIMATED";
    case "transcript_observed":
      return "DERIVED";
  }
}

// src/reporting/format.ts
function formatSimpleStatus(view) {
  const five = view.session.latestQuota?.fiveHour ? `${formatPct2(view.session.latestQuota.fiveHour.value.usedPercentage)}%` : "Unavailable";
  const seven = view.session.latestQuota?.sevenDay ? `${formatPct2(view.session.latestQuota.sevenDay.value.usedPercentage)}%` : "Unavailable";
  const monitoring = view.integration === "ACTIVE" ? "Active" : "Idle";
  const session = view.integration === "ACTIVE" || view.session.promptsObserved > 0 ? "Active" : "Idle";
  return [
    "PromptGauge",
    "",
    `Monitoring       ${monitoring}`,
    "",
    `5h usage         ${five}`,
    `7d usage         ${seven}`,
    "",
    `Prompts          ${view.session.promptsObserved}`,
    `Current session  ${session}`,
    ""
  ].join("\n");
}
function formatStatus(view, now) {
  const quota = view.session.latestQuota;
  const lines = [
    "PromptGauge",
    "",
    `Claude Code integration: ${view.integration}`,
    "",
    ...formatQuotaBlock("5-hour quota", quota?.fiveHour?.value, now, view.fiveHourLabel),
    "",
    ...formatQuotaBlock("7-day quota", quota?.sevenDay?.value, now, view.sevenDayLabel),
    "",
    ...formatQuotaBlock(
      "Spend limit (Claude apps gateway, not 5h/7d)",
      quota?.spendLimit?.value,
      now,
      quota?.spendLimit ? "unavailable" : "unavailable"
    ),
    "",
    ...formatCostBlock(quota),
    "",
    ...formatContextBlock(quota),
    "",
    "Current session",
    `Prompts observed: ${view.session.promptsObserved}`,
    "",
    "Latest prompt",
    ...view.latestPromptLines,
    "",
    "Circuit breaker (observe-only)",
    `State:      ${view.circuitBreaker.state}`,
    `Reason:     ${view.circuitBreaker.reason}`,
    `Action:     ${view.circuitBreaker.recommendedAction}`,
    "",
    "Burn detector",
    `Level:      ${view.burn.level}`,
    `Reason:     ${view.burn.reason}`
  ];
  return `${lines.join("\n")}
`;
}
function formatQuotaBlock(title, window, now, unavailableLabel) {
  if (!window) {
    return [`${title}: ${unavailableLabel}`, "Provenance: UNAVAILABLE"];
  }
  return [
    title,
    `Used:       ${formatPct2(window.usedPercentage)}%`,
    `Reset:      ${formatDurationUntil(epochSecondsToDate(window.resetsAtEpochSeconds), now)}`,
    "Source:     Claude Code",
    "Provenance: CLAUDE_REPORTED"
  ];
}
function formatCostBlock(snapshot) {
  const cost = snapshot?.estimatedApiCostUsd;
  if (!cost) {
    return [
      "Estimated API-equivalent cost (not subscription billing): unavailable",
      "Provenance: UNAVAILABLE"
    ];
  }
  return [
    "Estimated API-equivalent cost (not subscription billing)",
    `Session:    $${cost.value.toFixed(5)}`,
    `Provenance: ${displayProvenance(cost.provenance)}`
  ];
}
function formatContextBlock(snapshot) {
  const context = snapshot?.contextWindow;
  if (!context) {
    return [
      "Context window (latest API response, not per-prompt tokens): unavailable",
      "Provenance: UNAVAILABLE"
    ];
  }
  const used = context.usedPercentage === void 0 ? "unavailable" : `${formatPct2(context.usedPercentage)}%`;
  return [
    "Context window (latest API response, not per-prompt tokens)",
    `Used:       ${used}`,
    `Input:      ${context.totalInputTokens ?? "unavailable"}`,
    `Output:     ${context.totalOutputTokens ?? "unavailable"}`,
    "Provenance: CLAUDE_REPORTED"
  ];
}
function formatPct2(value) {
  return Number.isInteger(value) ? String(value) : value.toFixed(1);
}
function quotaUnavailableLabel(snapshot, window) {
  if (!snapshot) {
    return "unavailable";
  }
  if (window === "five" && !snapshot.fiveHour) {
    return "unavailable";
  }
  if (window === "seven" && !snapshot.sevenDay) {
    return "unavailable";
  }
  return "unavailable";
}
function formatLatestPrompt(summary) {
  const prompt = summary.latestPrompt;
  if (!prompt) {
    return [
      "ID:        none",
      "Started:   n/a",
      "Quota \u0394:   unavailable",
      "Est. API cost \u0394: unavailable",
      "Exact prompt tokens: UNAVAILABLE"
    ];
  }
  const delta = prompt.quotaDeltaFiveHour ? `${signed(prompt.quotaDeltaFiveHour.value)} pts (5h, ${displayProvenance(prompt.quotaDeltaFiveHour.provenance)}; not tokens)` : "unavailable";
  const cost = prompt.estimatedApiCostDelta ? `$${prompt.estimatedApiCostDelta.value.toFixed(5)} (${displayProvenance(prompt.estimatedApiCostDelta.provenance)})` : "unavailable";
  return [
    `ID:        ${prompt.promptId ?? "unknown"}`,
    `Started:   ${prompt.startedAt ?? "unknown"}`,
    `Quota \u0394:   ${delta}`,
    `Est. API cost \u0394: ${cost}`,
    "Exact prompt tokens: UNAVAILABLE"
  ];
}
function signed(value) {
  if (value > 0) {
    return `+${value.toFixed(1)}`;
  }
  return value.toFixed(1);
}

// src/reporting/status-report.ts
function buildStatusView(events, config, now) {
  const session = summarizeSession(events);
  const circuitBreaker = evaluateCircuitBreaker({
    snapshot: session.latestQuota,
    now,
    freshnessMs: config.freshnessMs,
    thresholds: config.thresholds,
    mode: config.mode
  });
  const burn = evaluateBurn({ events, now });
  const integration = integrationStatus(events, now, config.freshnessMs);
  return {
    integration,
    fiveHourLabel: quotaUnavailableLabel(session.latestQuota, "five"),
    sevenDayLabel: quotaUnavailableLabel(session.latestQuota, "seven"),
    session,
    circuitBreaker,
    burn,
    latestPromptLines: formatLatestPrompt(session)
  };
}
function renderStatus(events, config, now, simple = false) {
  const view = buildStatusView(events, config, now);
  return simple ? formatSimpleStatus(view) : formatStatus(view, now);
}
function integrationStatus(events, now, freshnessMs) {
  const last = events[events.length - 1];
  if (!last) {
    return "INACTIVE";
  }
  if (isStale(last.capturedAt, now, Math.max(freshnessMs, 24 * 60 * 60 * 1e3))) {
    return "INACTIVE";
  }
  return "ACTIVE";
}

// src/storage/jsonl.ts
var import_node_fs3 = __toESM(require("node:fs"), 1);

// src/claude/sanitizer.ts
var FORBIDDEN_KEYS = /* @__PURE__ */ new Set([
  "prompt",
  "tool_input",
  "tool_response",
  "last_assistant_message",
  "task_subject",
  "task_description",
  "transcript_path",
  "cwd",
  "command",
  "content",
  "current_dir",
  "project_dir",
  "background_tasks",
  "session_crons"
]);
function assertNoForbiddenFields(event) {
  for (const key of FORBIDDEN_KEYS) {
    if (key in event) {
      throw new Error(`refusing to persist forbidden field: ${key}`);
    }
  }
}

// src/core/privacy/allowlist.ts
var FORBIDDEN_KEYS2 = /* @__PURE__ */ new Set([
  "prompt",
  "tool_input",
  "tool_response",
  "last_assistant_message",
  "task_subject",
  "task_description",
  "transcript_path",
  "cwd",
  "current_dir",
  "project_dir",
  "added_dirs",
  "command",
  "content",
  "raw",
  "stdin",
  "session_crons",
  "background_tasks",
  "description"
]);
function findForbiddenKeys(value, trail = "") {
  if (Array.isArray(value)) {
    return value.flatMap((item, index) => findForbiddenKeys(item, `${trail}[${index}]`));
  }
  if (typeof value !== "object" || value === null) {
    return [];
  }
  const hits = [];
  for (const [key, child] of Object.entries(value)) {
    const next = trail ? `${trail}.${key}` : key;
    if (FORBIDDEN_KEYS2.has(key)) {
      hits.push(next);
    }
    hits.push(...findForbiddenKeys(child, next));
  }
  return hits;
}
function eventLooksPrivate(value) {
  const text = JSON.stringify(value);
  if (!text) {
    return false;
  }
  if (findForbiddenKeys(value).length > 0) {
    return true;
  }
  return text.includes("transcript_path") || text.includes("tool_input") || /"prompt"\s*:/.test(text);
}

// src/storage/paths.ts
var import_node_fs2 = __toESM(require("node:fs"), 1);
var import_node_os = __toESM(require("node:os"), 1);
var import_node_path3 = __toESM(require("node:path"), 1);
function resolveDataDir(env = process.env, home = import_node_os.default.homedir()) {
  if (env.PROMPTGAUGE_HOME && env.PROMPTGAUGE_HOME.length > 0) {
    return env.PROMPTGAUGE_HOME;
  }
  return import_node_path3.default.join(home, DEFAULT_DATA_DIR_NAME);
}
function resolvePaths(dataDir) {
  return {
    dataDir,
    eventsFile: import_node_path3.default.join(dataDir, EVENTS_FILE_NAME),
    configFile: import_node_path3.default.join(dataDir, CONFIG_FILE_NAME)
  };
}
function ensureDataDir(dataDir) {
  import_node_fs2.default.mkdirSync(dataDir, { recursive: true });
}

// src/storage/jsonl.ts
function appendEvents(eventsFile, events) {
  if (events.length === 0) {
    return;
  }
  ensureDataDir(pathDirname(eventsFile));
  const lines = events.map((event) => {
    assertNoForbiddenFields(event);
    const forbidden = findForbiddenKeys(event);
    if (forbidden.length > 0) {
      throw new Error(`refusing to persist forbidden field: ${forbidden[0]}`);
    }
    return JSON.stringify(event);
  }).join("\n");
  import_node_fs3.default.appendFileSync(eventsFile, `${lines}
`, { encoding: "utf8" });
}
function readEvents(eventsFile) {
  if (!import_node_fs3.default.existsSync(eventsFile)) {
    return { events: [], skippedCorruptLines: 0 };
  }
  const text = import_node_fs3.default.readFileSync(eventsFile, "utf8");
  if (text.trim().length === 0) {
    return { events: [], skippedCorruptLines: 0 };
  }
  const events = [];
  let skippedCorruptLines = 0;
  for (const line of text.split(/\r?\n/)) {
    if (line.trim().length === 0) {
      continue;
    }
    const parsed = parseJson(line);
    if (!parsed.ok || !isStoredEvent(parsed.value)) {
      skippedCorruptLines += 1;
      continue;
    }
    events.push(parsed.value);
  }
  return { events, skippedCorruptLines };
}
function pathDirname(filePath) {
  const idx = Math.max(filePath.lastIndexOf("/"), filePath.lastIndexOf("\\"));
  return idx === -1 ? "." : filePath.slice(0, idx);
}
function isStoredEvent(value) {
  if (typeof value !== "object" || value === null) {
    return false;
  }
  const record = value;
  return typeof record.type === "string" && typeof record.capturedAt === "string";
}

// src/core/privacy/project-id.ts
var import_node_crypto = require("node:crypto");
var import_node_path5 = __toESM(require("node:path"), 1);

// src/utils/platform.ts
var import_node_child_process = require("node:child_process");
var import_node_fs4 = __toESM(require("node:fs"), 1);
var import_node_os2 = __toESM(require("node:os"), 1);
var import_node_path4 = __toESM(require("node:path"), 1);
function isWindows(platform = process.platform) {
  return platform === "win32";
}
function normalizePathForCompare(filePath) {
  return import_node_path4.default.normalize(filePath).replaceAll("\\", "/");
}
function defaultHomeDir() {
  return import_node_os2.default.homedir();
}
function claudeConfigDir(home = defaultHomeDir()) {
  return import_node_path4.default.join(home, ".claude");
}
function quoteShellArg(arg) {
  if (arg.length === 0) {
    return '""';
  }
  if (!/[ \t"']/.test(arg)) {
    return arg;
  }
  return `"${arg.replaceAll('"', '\\"')}"`;
}
function locateClaudeBinary(env = process.env, home = defaultHomeDir()) {
  const fromPath = (0, import_node_child_process.spawnSync)("claude", ["--version"], {
    encoding: "utf8",
    timeout: 4e3,
    windowsHide: true,
    env
  });
  if (fromPath.status === 0) {
    return {
      found: true,
      version: (fromPath.stdout || fromPath.stderr).trim().split(/\r?\n/)[0],
      path: "claude"
    };
  }
  const candidates = [
    import_node_path4.default.join(home, "AppData", "Roaming", "npm", "claude.cmd"),
    import_node_path4.default.join(home, "AppData", "Roaming", "npm", "claude"),
    import_node_path4.default.join(home, "AppData", "Roaming", "npm", "claude.exe"),
    import_node_path4.default.join(home, ".local", "bin", "claude.exe"),
    import_node_path4.default.join(home, ".local", "bin", "claude.cmd"),
    import_node_path4.default.join(home, ".local", "bin", "claude"),
    import_node_path4.default.join(home, "AppData", "Local", "Programs", "claude", "claude.exe"),
    "/usr/local/bin/claude",
    "/opt/homebrew/bin/claude"
  ];
  if (env.APPDATA) {
    candidates.unshift(import_node_path4.default.join(env.APPDATA, "npm", "claude.cmd"));
  }
  for (const candidate of candidates) {
    if (!import_node_fs4.default.existsSync(candidate)) {
      continue;
    }
    const result = (0, import_node_child_process.spawnSync)(candidate, ["--version"], {
      encoding: "utf8",
      timeout: 4e3,
      windowsHide: true,
      env,
      shell: isWindows()
    });
    if (result.status === 0) {
      return {
        found: true,
        version: (result.stdout || result.stderr).trim().split(/\r?\n/)[0],
        path: candidate
      };
    }
    return { found: true, path: candidate };
  }
  return { found: false };
}

// src/core/privacy/project-id.ts
function projectIdentityFromPath(projectPath) {
  const normalized = normalizePathForCompare(projectPath).replace(/\/+$/, "");
  const projectKey = (0, import_node_crypto.createHash)("sha256").update(normalized.toLowerCase()).digest("hex").slice(0, 16);
  const projectBasename = import_node_path5.default.posix.basename(normalized) || import_node_path5.default.basename(projectPath);
  return { projectKey, projectBasename };
}

// src/claude/parsers/hooks.ts
function looksLikeHook(payload) {
  const name = asString(payload.hook_event_name);
  return Boolean(name) && name !== "Status";
}
function parseHook(payload, capturedAt) {
  if (!isRecord(payload)) {
    return { ok: false, error: "hook payload is not an object" };
  }
  const hookEventName = asString(payload.hook_event_name);
  if (!hookEventName) {
    return { ok: false, error: "missing hook_event_name" };
  }
  const sessionId = asString(payload.session_id);
  const promptId = asString(payload.prompt_id);
  const cwd = asString(payload.cwd);
  const project = cwd ? projectIdentityFromPath(cwd) : void 0;
  const envelope = {
    capturedAt,
    ingestSource: "hook",
    sessionId,
    promptId
  };
  const projectFields = {
    projectKey: project?.projectKey,
    projectBasename: project?.projectBasename
  };
  switch (hookEventName) {
    case "UserPromptSubmit":
      return {
        ok: true,
        events: [
          {
            ...envelope,
            ...projectFields,
            type: "prompt_lifecycle",
            phase: "start",
            hookEventName
          }
        ]
      };
    case "Stop":
      return {
        ok: true,
        events: [
          {
            ...envelope,
            ...projectFields,
            type: "prompt_lifecycle",
            phase: "stop",
            hookEventName,
            backgroundTaskCount: arrayCount(payload.background_tasks)
          }
        ]
      };
    case "StopFailure":
      return {
        ok: true,
        events: [
          {
            ...envelope,
            ...projectFields,
            type: "prompt_lifecycle",
            phase: "stop_failure",
            hookEventName
          }
        ]
      };
    case "PreToolUse":
      return {
        ok: true,
        events: [
          {
            ...envelope,
            type: "tool_activity",
            phase: "pre",
            toolName: asString(payload.tool_name),
            toolUseId: asString(payload.tool_use_id)
          }
        ]
      };
    case "PostToolUse":
      return {
        ok: true,
        events: [
          {
            ...envelope,
            type: "tool_activity",
            phase: "post",
            toolName: asString(payload.tool_name),
            toolUseId: asString(payload.tool_use_id),
            durationMs: asFiniteNumber(payload.duration_ms)
          }
        ]
      };
    case "PostToolUseFailure":
      return {
        ok: true,
        events: [
          {
            ...envelope,
            type: "tool_activity",
            phase: "post_failure",
            toolName: asString(payload.tool_name),
            toolUseId: asString(payload.tool_use_id)
          }
        ]
      };
    case "SubagentStart":
      return {
        ok: true,
        events: [
          {
            ...envelope,
            type: "subagent_activity",
            phase: "start",
            agentId: asString(payload.agent_id),
            agentType: asString(payload.agent_type)
          }
        ]
      };
    case "SubagentStop":
      return {
        ok: true,
        events: [
          {
            ...envelope,
            type: "subagent_activity",
            phase: "stop",
            agentId: asString(payload.agent_id),
            agentType: asString(payload.agent_type)
          }
        ]
      };
    case "TaskCreated":
      return {
        ok: true,
        events: [
          {
            ...envelope,
            type: "task_lifecycle",
            phase: "created",
            taskId: asString(payload.task_id)
          }
        ]
      };
    case "TaskCompleted":
      return {
        ok: true,
        events: [
          {
            ...envelope,
            type: "task_lifecycle",
            phase: "completed",
            taskId: asString(payload.task_id)
          }
        ]
      };
    default:
      return { ok: true, events: [] };
  }
}
function arrayCount(value) {
  return Array.isArray(value) ? value.length : void 0;
}

// src/claude/parsers/statusline.ts
function looksLikeStatusLine(payload) {
  if (asString(payload.hook_event_name) === "Status") {
    return true;
  }
  if (asString(payload.hook_event_name)) {
    return false;
  }
  return Boolean(payload.model) || Boolean(payload.rate_limits) || Boolean(payload.context_window) || Boolean(payload.prompt_cache);
}
function parseStatusLine(payload, capturedAt) {
  if (!isRecord(payload)) {
    return { ok: false, error: "status payload is not an object" };
  }
  const rateLimits = isRecord(payload.rate_limits) ? payload.rate_limits : void 0;
  const modelRaw = isRecord(payload.model) ? payload.model : void 0;
  const costRaw = isRecord(payload.cost) ? payload.cost : void 0;
  const workspace = isRecord(payload.workspace) ? payload.workspace : void 0;
  const projectPath = asString(workspace?.project_dir);
  const project = projectPath ? projectIdentityFromPath(projectPath) : void 0;
  const event = {
    type: "quota_snapshot",
    capturedAt,
    ingestSource: "statusline",
    sessionId: asString(payload.session_id),
    promptId: asString(payload.prompt_id),
    claudeVersion: asString(payload.version),
    model: modelRaw ? {
      id: asString(modelRaw.id),
      displayName: asString(modelRaw.display_name)
    } : void 0,
    fiveHour: parseWindow(rateLimits?.five_hour, { maxPercent: 100 }),
    sevenDay: parseWindow(rateLimits?.seven_day, { maxPercent: 100 }),
    spendLimit: parseWindow(rateLimits?.spend_limit, { maxPercent: Number.POSITIVE_INFINITY }),
    estimatedApiCostUsd: asFiniteNumber(costRaw?.total_cost_usd),
    contextWindow: parseContextWindow(payload.context_window),
    promptCache: parsePromptCache(payload.prompt_cache),
    projectKey: project?.projectKey,
    projectBasename: project?.projectBasename,
    provenance: "claude_reported",
    source: "claude_statusline"
  };
  return {
    ok: true,
    sessionId: event.sessionId,
    promptId: event.promptId,
    event
  };
}
function parseWindow(value, options) {
  if (!isRecord(value)) {
    return void 0;
  }
  const usedPercentage = asFiniteNumber(value.used_percentage);
  const resetsAtEpochSeconds = asFiniteNumber(value.resets_at);
  if (usedPercentage === void 0 || resetsAtEpochSeconds === void 0) {
    return void 0;
  }
  if (usedPercentage < 0 || usedPercentage > options.maxPercent) {
    return void 0;
  }
  return { usedPercentage, resetsAtEpochSeconds };
}
function parsePromptCache(value) {
  if (!isRecord(value)) {
    return void 0;
  }
  const ttlRaw = asString(value.ttl);
  const ttl = ttlRaw === "5m" || ttlRaw === "1h" ? ttlRaw : void 0;
  const hitRatio = asFiniteNumber(value.hit_ratio);
  const telemetry = {
    warm: asBoolean(value.warm),
    cachingObserved: asBoolean(value.caching_observed),
    ttl,
    expiresAtEpochSeconds: asFiniteNumber(value.expires_at),
    requests: asFiniteNumber(value.requests),
    misses: asFiniteNumber(value.misses),
    expectedRebuilds: asFiniteNumber(value.expected_rebuilds),
    hitRatio: hitRatio !== void 0 && hitRatio >= 0 && hitRatio <= 1 ? hitRatio : void 0,
    cacheWriteTokens: asFiniteNumber(value.cache_write_tokens),
    missRecacheTokens: asFiniteNumber(value.miss_recache_tokens),
    recacheTokensIfCold: asFiniteNumber(value.recache_tokens_if_cold)
  };
  if (Object.values(telemetry).every((item) => item === void 0)) {
    return void 0;
  }
  return telemetry;
}
function parseContextWindow(value) {
  if (!isRecord(value)) {
    return void 0;
  }
  const currentUsage = parseCurrentUsage(value.current_usage);
  const telemetry = {
    totalInputTokens: asFiniteNumber(value.total_input_tokens),
    totalOutputTokens: asFiniteNumber(value.total_output_tokens),
    contextWindowSize: asFiniteNumber(value.context_window_size),
    usedPercentage: asFiniteNumber(value.used_percentage),
    remainingPercentage: asFiniteNumber(value.remaining_percentage),
    currentUsage,
    derivedCacheHitRatio: cacheHitRatio(currentUsage)
  };
  if (Object.values(telemetry).every((item) => item === void 0)) {
    return void 0;
  }
  return telemetry;
}
function parseCurrentUsage(value) {
  if (value === null || !isRecord(value)) {
    return void 0;
  }
  const usage = {
    inputTokens: asFiniteNumber(value.input_tokens),
    outputTokens: asFiniteNumber(value.output_tokens),
    cacheCreationInputTokens: asFiniteNumber(value.cache_creation_input_tokens),
    cacheReadInputTokens: asFiniteNumber(value.cache_read_input_tokens)
  };
  if (Object.values(usage).every((item) => item === void 0)) {
    return void 0;
  }
  return usage;
}
function cacheHitRatio(usage) {
  if (!usage) {
    return void 0;
  }
  const reads = usage.cacheReadInputTokens ?? 0;
  const writes = usage.cacheCreationInputTokens ?? 0;
  const total = reads + writes;
  if (total <= 0) {
    return void 0;
  }
  return reads / total;
}

// src/claude/parsers/ingest.ts
function ingestPayload(raw, capturedAt) {
  const parsed = parseJson(raw);
  if (!parsed.ok) {
    return {
      kind: "unknown",
      printStatusLine: false,
      events: [
        {
          type: "ingest_error",
          capturedAt,
          ingestSource: "cli",
          reason: parsed.error
        }
      ],
      error: parsed.error
    };
  }
  if (!isRecord(parsed.value)) {
    return {
      kind: "unknown",
      printStatusLine: false,
      events: [
        {
          type: "ingest_error",
          capturedAt,
          ingestSource: "cli",
          reason: "payload is not a JSON object"
        }
      ],
      error: "payload is not a JSON object"
    };
  }
  if (looksLikeHook(parsed.value)) {
    const hook = parseHook(parsed.value, capturedAt);
    if (!hook.ok) {
      return {
        kind: "hook",
        printStatusLine: false,
        events: [
          {
            type: "ingest_error",
            capturedAt,
            ingestSource: "hook",
            reason: hook.error
          }
        ],
        error: hook.error
      };
    }
    return { kind: "hook", printStatusLine: false, events: hook.events };
  }
  if (looksLikeStatusLine(parsed.value)) {
    const status = parseStatusLine(parsed.value, capturedAt);
    if (!status.ok) {
      return {
        kind: "statusline",
        printStatusLine: true,
        events: [
          {
            type: "ingest_error",
            capturedAt,
            ingestSource: "statusline",
            reason: status.error
          }
        ],
        error: status.error
      };
    }
    return { kind: "statusline", printStatusLine: true, events: [status.event] };
  }
  return {
    kind: "unknown",
    printStatusLine: false,
    events: [
      {
        type: "ingest_error",
        capturedAt,
        ingestSource: "cli",
        reason: "unrecognized payload"
      }
    ],
    error: "unrecognized payload"
  };
}

// src/cli/commands/collect.ts
function collectFromStdin(raw, eventsFile, now) {
  const result = ingestPayload(raw, now.toISOString());
  appendEvents(eventsFile, result.events);
  if (!result.printStatusLine) {
    return { result, stdout: "" };
  }
  const snapshot = result.events.find((event) => event.type === "quota_snapshot");
  return { result, stdout: `${formatStatusLine(snapshot, now)}
` };
}
function formatStatusLine(event, now) {
  if (!event) {
    return "PromptGauge  Live subscription quota unavailable";
  }
  const parts = ["PromptGauge"];
  if (event.fiveHour) {
    parts.push(
      `5h ${formatPct2(event.fiveHour.usedPercentage)}% ${formatDurationUntil(epochSecondsToDate(event.fiveHour.resetsAtEpochSeconds), now)}`
    );
  } else {
    parts.push("5h unavailable");
  }
  if (event.sevenDay) {
    parts.push(
      `7d ${formatPct2(event.sevenDay.usedPercentage)}% ${formatDurationUntil(epochSecondsToDate(event.sevenDay.resetsAtEpochSeconds), now)}`
    );
  } else {
    parts.push("7d unavailable");
  }
  return parts.join("  ");
}

// src/cli/commands/doctor.ts
var import_node_fs8 = __toESM(require("node:fs"), 1);
var import_node_path9 = __toESM(require("node:path"), 1);

// src/utils/redact.ts
function looksLikeSecretFilename(name) {
  const lower = name.toLowerCase();
  return lower.includes("credential") || lower.includes(".env") || lower.endsWith(".pem") || lower.endsWith(".key");
}

// src/claude/statusline/plan.ts
function isPromptGaugeWrapperCommand(command) {
  if (!command) {
    return false;
  }
  return command.includes(WRAPPER_MARKER) || /\bstatusline\s+run\b/.test(command);
}
function preserveDisplayProps(previous) {
  if (!previous) {
    return {};
  }
  const extra = {};
  if (typeof previous.padding === "number") {
    extra.padding = previous.padding;
  }
  if (typeof previous.refreshInterval === "number") {
    extra.refreshInterval = previous.refreshInterval;
  }
  if (typeof previous.hideVimModeIndicator === "boolean") {
    extra.hideVimModeIndicator = previous.hideVimModeIndicator;
  }
  return extra;
}
function planInstall(settings, wrapperCommand) {
  const current = { ...settings ?? {} };
  const existing = asStatusLine(current.statusLine);
  if (existing && isPromptGaugeWrapperCommand(existing.command)) {
    return { alreadyInstalled: true, previous: existing, nextSettings: current };
  }
  const previous = existing;
  current.statusLine = {
    type: "command",
    command: wrapperCommand,
    ...preserveDisplayProps(previous)
  };
  return { alreadyInstalled: false, previous, nextSettings: current };
}
function planUninstall(settings, state) {
  const current = { ...settings ?? {} };
  const existing = asStatusLine(current.statusLine);
  if (!existing || !isPromptGaugeWrapperCommand(existing.command)) {
    return { nextSettings: current, restored: false };
  }
  if (state?.previousExisted && state.previousStatusLine) {
    current.statusLine = state.previousStatusLine;
  } else {
    delete current.statusLine;
  }
  return { nextSettings: current, restored: true };
}
function asStatusLine(value) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return null;
  }
  return value;
}

// src/claude/statusline/install.ts
var import_node_fs6 = __toESM(require("node:fs"), 1);
var import_node_path7 = __toESM(require("node:path"), 1);

// src/utils/atomic-write.ts
var import_node_fs5 = __toESM(require("node:fs"), 1);
var import_node_path6 = __toESM(require("node:path"), 1);
function writeTextAtomic(filePath, text) {
  const dir = import_node_path6.default.dirname(filePath);
  import_node_fs5.default.mkdirSync(dir, { recursive: true });
  const tmp = import_node_path6.default.join(dir, `${import_node_path6.default.basename(filePath)}.${process.pid}.${Date.now()}.tmp`);
  import_node_fs5.default.writeFileSync(tmp, text, { encoding: "utf8" });
  try {
    import_node_fs5.default.renameSync(tmp, filePath);
  } catch {
    import_node_fs5.default.copyFileSync(tmp, filePath);
    import_node_fs5.default.unlinkSync(tmp);
  }
}
function writeJsonAtomic(filePath, value) {
  writeTextAtomic(filePath, `${JSON.stringify(value, null, 2)}
`);
}
function copyFileAtomic(from, to) {
  const dir = import_node_path6.default.dirname(to);
  import_node_fs5.default.mkdirSync(dir, { recursive: true });
  const tmp = `${to}.${process.pid}.copytmp`;
  import_node_fs5.default.copyFileSync(from, tmp);
  try {
    import_node_fs5.default.renameSync(tmp, to);
  } catch {
    import_node_fs5.default.copyFileSync(tmp, to);
    import_node_fs5.default.unlinkSync(tmp);
  }
}

// src/claude/statusline/install.ts
function settingsPathFor(io) {
  const override = io.env?.CLAUDE_CONFIG_DIR;
  const dir = override && override.length > 0 ? override : claudeConfigDir(io.home);
  return import_node_path7.default.join(dir, "settings.json");
}
function statePathFor(dataDir) {
  return import_node_path7.default.join(dataDir, STATUSLINE_STATE_FILE_NAME);
}
function resolveWrapperCommand(io) {
  const node = io.nodeExecutable ?? process.execPath;
  const cli = io.cliEntry ?? defaultCliEntry();
  return `${quoteShellArg(node)} ${quoteShellArg(cli)} statusline run ${WRAPPER_MARKER}`;
}
function defaultCliEntry() {
  return resolveCliEntry();
}
function readSettingsFile(filePath) {
  if (!import_node_fs6.default.existsSync(filePath)) {
    return { ok: true, value: {}, existed: false };
  }
  const text = import_node_fs6.default.readFileSync(filePath, "utf8");
  const parsed = parseJson(text);
  if (!parsed.ok || typeof parsed.value !== "object" || parsed.value === null) {
    return { ok: false, error: "settings.json is malformed; refusing to overwrite", existed: true };
  }
  return { ok: true, value: parsed.value, existed: true };
}
function readInstallState(dataDir) {
  const file = statePathFor(dataDir);
  if (!import_node_fs6.default.existsSync(file)) {
    return void 0;
  }
  const parsed = parseJson(import_node_fs6.default.readFileSync(file, "utf8"));
  if (!parsed.ok || typeof parsed.value !== "object" || parsed.value === null) {
    return void 0;
  }
  return parsed.value;
}
function installStatusLine(io) {
  const settingsPath = settingsPathFor(io);
  const wrapperCommand = resolveWrapperCommand(io);
  const loaded = readSettingsFile(settingsPath);
  if (!loaded.ok) {
    return {
      ok: false,
      alreadyInstalled: false,
      settingsPath,
      wrapperCommand,
      preservedExisting: false,
      message: loaded.error
    };
  }
  const planned = planInstall(loaded.value, wrapperCommand);
  if (planned.alreadyInstalled) {
    const state2 = readInstallState(io.dataDir);
    return {
      ok: true,
      alreadyInstalled: true,
      settingsPath,
      wrapperCommand: planned.previous?.command ?? wrapperCommand,
      preservedExisting: Boolean(state2?.previousExisted),
      message: "PromptGauge status line wrapper already installed."
    };
  }
  import_node_fs6.default.mkdirSync(import_node_path7.default.dirname(settingsPath), { recursive: true });
  let backupPath;
  if (loaded.existed) {
    backupPath = `${settingsPath}.promptgauge-backup`;
    copyFileAtomic(settingsPath, backupPath);
    copyFileAtomic(settingsPath, `${settingsPath}.promptgauge-backup-${Date.now()}`);
  }
  writeJsonAtomic(settingsPath, planned.nextSettings);
  const state = {
    version: 1,
    installedAt: (io.now ?? (() => /* @__PURE__ */ new Date()))().toISOString(),
    wrapperCommand,
    previousExisted: Boolean(planned.previous),
    previousStatusLine: planned.previous
  };
  writeJsonAtomic(statePathFor(io.dataDir), state);
  return {
    ok: true,
    alreadyInstalled: false,
    settingsPath,
    backupPath,
    wrapperCommand,
    preservedExisting: Boolean(planned.previous),
    message: planned.previous ? "Installed PromptGauge wrapper around the existing statusLine." : "Installed PromptGauge statusLine; no previous statusLine was present."
  };
}
function uninstallStatusLine(io) {
  const settingsPath = settingsPathFor(io);
  const wrapperCommand = resolveWrapperCommand(io);
  const loaded = readSettingsFile(settingsPath);
  if (!loaded.ok) {
    return {
      ok: false,
      alreadyInstalled: false,
      settingsPath,
      wrapperCommand,
      preservedExisting: false,
      message: loaded.error
    };
  }
  const state = readInstallState(io.dataDir);
  const planned = planUninstall(loaded.value, state);
  if (!planned.restored) {
    return {
      ok: true,
      alreadyInstalled: false,
      settingsPath,
      wrapperCommand,
      preservedExisting: false,
      message: "PromptGauge statusLine wrapper was not installed."
    };
  }
  writeJsonAtomic(settingsPath, planned.nextSettings);
  const stateFile = statePathFor(io.dataDir);
  if (import_node_fs6.default.existsSync(stateFile)) {
    import_node_fs6.default.unlinkSync(stateFile);
  }
  return {
    ok: true,
    alreadyInstalled: false,
    settingsPath,
    wrapperCommand,
    preservedExisting: Boolean(state?.previousExisted),
    message: state?.previousExisted ? "Restored the previous statusLine configuration." : "Removed the PromptGauge statusLine entry."
  };
}
function describeStatusLine(io) {
  const settingsPath = settingsPathFor(io);
  const loaded = readSettingsFile(settingsPath);
  const state = readInstallState(io.dataDir);
  const lines = ["PromptGauge statusline status", "", `Settings:  ${settingsPath}`];
  if (!loaded.ok) {
    lines.push(`JSON:      FAIL (${loaded.error})`);
    return `${lines.join("\n")}
`;
  }
  if (!loaded.existed) {
    lines.push("JSON:      no settings.json yet");
    lines.push("Wrapper:   not installed");
    return `${lines.join("\n")}
`;
  }
  const command = loaded.value.statusLine && typeof loaded.value.statusLine === "object" && loaded.value.statusLine !== null && "command" in loaded.value.statusLine ? String(loaded.value.statusLine.command ?? "") : "";
  const wrapped = isPromptGaugeWrapperCommand(command);
  lines.push(`Wrapper:   ${wrapped ? "installed" : "not installed"}`);
  if (command) {
    lines.push(`Command:   ${command}`);
  }
  if (wrapped && state?.previousExisted) {
    lines.push(`Preserved: ${state.previousStatusLine?.command ?? "(previous statusLine object)"}`);
  } else if (wrapped) {
    lines.push("Preserved: N/A (no previous statusLine)");
  } else if (command) {
    lines.push("Preserved: existing statusLine is untouched");
  } else {
    lines.push("Preserved: N/A");
  }
  return `${lines.join("\n")}
`;
}

// src/claude/hooks/plan.ts
var HOOK_EVENTS = ["UserPromptSubmit", "Stop"];
function isPromptGaugeHookCommand(command) {
  if (!command) {
    return false;
  }
  return command.includes(HOOK_MARKER);
}
function promptGaugeMatcherGroup(hookCommand) {
  return {
    hooks: [
      {
        type: "command",
        command: hookCommand,
        timeout: 10
      }
    ]
  };
}
function planHooksInstall(settings, hookCommand) {
  const current = { ...settings ?? {} };
  const hooks = cloneHooks(current.hooks);
  const previousExisted = Object.keys(hooks).length > 0;
  if (hasPromptGaugeHooks(hooks, hookCommand)) {
    return { alreadyInstalled: true, previousExisted, nextSettings: current };
  }
  for (const event of HOOK_EVENTS) {
    const groups = hooks[event] ? [...hooks[event]] : [];
    groups.push(promptGaugeMatcherGroup(hookCommand));
    hooks[event] = groups;
  }
  current.hooks = hooks;
  return { alreadyInstalled: false, previousExisted, nextSettings: current };
}
function planHooksUninstall(settings) {
  const current = { ...settings ?? {} };
  const hooks = cloneHooks(current.hooks);
  if (!hasPromptGaugeHooks(hooks)) {
    return { nextSettings: current, restored: false };
  }
  const next = {};
  for (const [event, groups] of Object.entries(hooks)) {
    const kept = groups.map((group) => stripPromptGaugeHandlers(group)).filter((group) => group !== void 0);
    if (kept.length > 0) {
      next[event] = kept;
    }
  }
  if (Object.keys(next).length > 0) {
    current.hooks = next;
  } else {
    delete current.hooks;
  }
  return { nextSettings: current, restored: true };
}
function hasPromptGaugeHooks(hooks, hookCommand) {
  for (const event of HOOK_EVENTS) {
    for (const group of hooks[event] ?? []) {
      for (const handler of group.hooks ?? []) {
        if (!isPromptGaugeHookCommand(handler.command)) {
          continue;
        }
        if (!hookCommand || handler.command === hookCommand) {
          return true;
        }
        if (hookCommand && isPromptGaugeHookCommand(handler.command)) {
          return true;
        }
      }
    }
  }
  return false;
}
function stripPromptGaugeHandlers(group) {
  const handlers = (group.hooks ?? []).filter(
    (handler) => !isPromptGaugeHookCommand(handler.command)
  );
  if (handlers.length === 0 && (group.hooks ?? []).some((handler) => isPromptGaugeHookCommand(handler.command))) {
    const leftoverKeys = Object.keys(group).filter((key) => key !== "hooks");
    if (leftoverKeys.length === 0) {
      return void 0;
    }
  }
  if (handlers.length === (group.hooks ?? []).length) {
    return group;
  }
  if (handlers.length === 0) {
    return void 0;
  }
  return { ...group, hooks: handlers };
}
function cloneHooks(value) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return {};
  }
  const next = {};
  for (const [event, groups] of Object.entries(value)) {
    if (!Array.isArray(groups)) {
      continue;
    }
    next[event] = groups.filter(
      (group) => typeof group === "object" && group !== null
    );
  }
  return next;
}

// src/claude/plugin/root.ts
var import_node_fs7 = __toESM(require("node:fs"), 1);
var import_node_path8 = __toESM(require("node:path"), 1);
function detectPluginRoot(env = process.env, cliEntry) {
  const fromEnv = env.CLAUDE_PLUGIN_ROOT?.trim();
  if (fromEnv && isPluginRoot(fromEnv)) {
    return import_node_path8.default.resolve(fromEnv);
  }
  let dir = cliEntry ? import_node_path8.default.dirname(import_node_path8.default.resolve(cliEntry)) : void 0;
  for (let i = 0; i < 5 && dir; i += 1) {
    if (isPluginRoot(dir)) {
      return dir;
    }
    dir = import_node_path8.default.dirname(dir);
  }
  return void 0;
}
function isPluginRoot(dir) {
  return import_node_fs7.default.existsSync(import_node_path8.default.join(dir, ".claude-plugin", "plugin.json"));
}
function pluginRuntimePath(pluginRoot) {
  return import_node_path8.default.join(pluginRoot, "runtime", "promptgauge.cjs");
}
function pluginHasRuntime(pluginRoot) {
  return import_node_fs7.default.existsSync(pluginRuntimePath(pluginRoot));
}
function pluginHasNativeHooks(pluginRoot) {
  const file = import_node_path8.default.join(pluginRoot, "hooks", "hooks.json");
  if (!import_node_fs7.default.existsSync(file)) {
    return false;
  }
  try {
    const parsed = JSON.parse(import_node_fs7.default.readFileSync(file, "utf8"));
    return Boolean(parsed.hooks?.UserPromptSubmit && parsed.hooks?.Stop);
  } catch {
    return false;
  }
}

// src/reporting/prompts.ts
function completedPromptIds(events) {
  const started = /* @__PURE__ */ new Set();
  const completed = [];
  const seen = /* @__PURE__ */ new Set();
  for (const event of events) {
    if (event.type !== "prompt_lifecycle" || !event.promptId) {
      continue;
    }
    if (event.phase === "start") {
      started.add(event.promptId);
    }
    if ((event.phase === "stop" || event.phase === "stop_failure") && started.has(event.promptId) && !seen.has(event.promptId)) {
      seen.add(event.promptId);
      completed.push(event.promptId);
    }
  }
  return completed;
}
function formatPrompts(events, limit) {
  const cap = Number.isFinite(limit) && limit > 0 ? Math.floor(limit) : 10;
  const ids = completedPromptIds(events).slice(-cap);
  if (ids.length === 0) {
    return "No completed prompt records yet.\n";
  }
  const records = ids.map((id) => buildPromptUsageRecord(events, id));
  const lines = [
    "PromptGauge \u2014 Recent Prompts",
    "",
    pad("Prompt", 12) + pad("Duration", 12) + pad("5H \u0394", 10) + pad("7D \u0394", 10) + "Cost \u0394",
    "--------------------------------------------------",
    ...records.map(formatRow),
    "",
    "* estimated API-equivalent session cost delta",
    "N/A means UNAVAILABLE (not zero). Snapshots are correlated, not simultaneous with hooks.",
    "Exact prompt token consumption is UNAVAILABLE."
  ];
  return `${lines.join("\n")}
`;
}
function formatRow(record) {
  const id = shorten(record.promptId);
  const duration = record.durationMs === void 0 ? "N/A" : formatShortDuration(record.durationMs);
  return pad(id, 12) + pad(duration, 12) + pad(formatDeltaPct(record.fiveHour?.delta?.value), 10) + pad(formatDeltaPct(record.sevenDay?.delta?.value), 10) + formatCost(record);
}
function formatDeltaPct(value) {
  if (value === void 0) {
    return "N/A";
  }
  const sign = value > 0 ? "+" : "";
  return `${sign}${formatPct2(value)}%`;
}
function formatShortDuration(ms) {
  if (ms < 6e4) {
    return `${Math.max(0, Math.round(ms / 1e3))}s`;
  }
  if (ms < 36e5) {
    return `${Math.round(ms / 6e4)}m`;
  }
  return `${Math.round(ms / 36e5)}h`;
}
function formatCost(record) {
  if (!record.estimatedSessionCostDelta) {
    return "N/A";
  }
  return `$${record.estimatedSessionCostDelta.value.toFixed(3)}*`;
}
function shorten(promptId) {
  if (promptId.length <= 8) {
    return promptId;
  }
  return `...${promptId.slice(-4)}`;
}
function pad(value, width) {
  return value.length >= width ? `${value} ` : value.padEnd(width);
}

// src/cli/commands/doctor.ts
function runDoctor(ctx) {
  return [
    pluginCheck(ctx),
    nodeCheck(ctx.nodeVersion),
    claudeBinaryCheck(ctx),
    telemetryEvidenceCheck(ctx),
    claudeSettingsCheck(ctx),
    statusLineIntegrationCheck(ctx),
    existingStatusLinePreservedCheck(ctx),
    hookIntegrationCheck(ctx),
    fiveHourTelemetryCheck(ctx),
    sevenDayTelemetryCheck(ctx),
    costTelemetryCheck(ctx),
    contextTelemetryCheck(ctx),
    promptLifecycleCheck(ctx),
    promptAttributionCheck(ctx),
    privacyCheck(ctx),
    statusDataCheck(ctx),
    storageCheck(ctx),
    permissionsCheck(ctx)
  ];
}
function formatDoctor(checks) {
  const lines = ["PromptGauge Doctor", ""];
  const width = Math.max(...checks.map((check) => check.name.length));
  for (const check of checks) {
    lines.push(`${check.name.padEnd(width)}  ${check.status.padEnd(12)}  ${check.detail}`);
  }
  lines.push("");
  lines.push("No credentials inspected.");
  return `${lines.join("\n")}
`;
}
function pluginCheck(ctx) {
  if (!ctx.pluginRoot) {
    return { name: "Plugin", status: "WARN", detail: "not running from a plugin install" };
  }
  if (!pluginHasRuntime(ctx.pluginRoot)) {
    return { name: "Plugin", status: "FAIL", detail: "runtime missing" };
  }
  if (!pluginHasNativeHooks(ctx.pluginRoot)) {
    return { name: "Plugin", status: "WARN", detail: "plugin hooks.json missing" };
  }
  return { name: "Plugin", status: "PASS", detail: "plugin runtime and hooks present" };
}
function nodeCheck(version) {
  const major = Number.parseInt(version.replace(/^v/, "").split(".")[0] ?? "0", 10);
  if (major >= 22) {
    return { name: "Node", status: "PASS", detail: version };
  }
  return { name: "Node", status: "FAIL", detail: `${version} (need >= 22)` };
}
function resolveClaudeConfigDir(ctx) {
  const override = ctx.env.CLAUDE_CONFIG_DIR;
  if (override && override.length > 0) {
    return override;
  }
  return claudeConfigDir(ctx.home);
}
function claudeBinaryCheck(ctx) {
  const probe = ctx.claudeVersionCommand ?? (() => locateClaudeBinary(ctx.env, ctx.home));
  const result = probe();
  const found = result.ok === true || result.found === true;
  if (found) {
    return {
      name: "Claude Code binary",
      status: "PASS",
      detail: result.version ?? result.path ?? "claude command found"
    };
  }
  const configDir = resolveClaudeConfigDir(ctx);
  if (import_node_fs8.default.existsSync(configDir) && import_node_fs8.default.statSync(configDir).isDirectory()) {
    return {
      name: "Claude Code binary",
      status: "WARN",
      detail: "config directory present; claude binary not on PATH"
    };
  }
  return { name: "Claude Code binary", status: "FAIL", detail: "claude command not found" };
}
function claudeSettingsCheck(ctx) {
  const settingsPath = import_node_path9.default.join(resolveClaudeConfigDir(ctx), "settings.json");
  if (!import_node_fs8.default.existsSync(settingsPath)) {
    return { name: "Claude settings", status: "WARN", detail: "no settings.json found" };
  }
  if (looksLikeSecretFilename(import_node_path9.default.basename(settingsPath))) {
    return { name: "Claude settings", status: "FAIL", detail: "refused to inspect a secret file" };
  }
  const loaded = readSettingsFile(settingsPath);
  if (!loaded.ok) {
    return { name: "Claude settings", status: "FAIL", detail: loaded.error };
  }
  return { name: "Claude settings", status: "PASS", detail: settingsPath };
}
function statusLineIntegrationCheck(ctx) {
  const settingsPath = import_node_path9.default.join(resolveClaudeConfigDir(ctx), "settings.json");
  const loaded = readSettingsFile(settingsPath);
  if (!loaded.ok) {
    return { name: "PromptGauge statusLine integration", status: "FAIL", detail: loaded.error };
  }
  if (!loaded.existed) {
    return {
      name: "PromptGauge statusLine integration",
      status: "WARN",
      detail: "not installed"
    };
  }
  const command = statusLineCommand(loaded.value);
  if (isPromptGaugeWrapperCommand(command)) {
    return {
      name: "PromptGauge statusLine integration",
      status: "PASS",
      detail: "wrapper installed"
    };
  }
  return {
    name: "PromptGauge statusLine integration",
    status: "WARN",
    detail: command ? "statusLine present but not wrapped" : "no statusLine configured"
  };
}
function existingStatusLinePreservedCheck(ctx) {
  const state = readInstallState(ctx.dataDir);
  const settingsPath = import_node_path9.default.join(resolveClaudeConfigDir(ctx), "settings.json");
  const loaded = readSettingsFile(settingsPath);
  const command = loaded.ok ? statusLineCommand(loaded.value) : "";
  if (!isPromptGaugeWrapperCommand(command)) {
    return {
      name: "Existing statusLine preserved",
      status: "N/A",
      detail: "PromptGauge wrapper is not installed"
    };
  }
  if (state?.previousExisted) {
    return {
      name: "Existing statusLine preserved",
      status: "PASS",
      detail: state.previousStatusLine?.command ?? "previous statusLine stored"
    };
  }
  return {
    name: "Existing statusLine preserved",
    status: "N/A",
    detail: "no previous statusLine"
  };
}
function telemetryEvidenceCheck(ctx) {
  const summary = summarizeSession(ctx.events);
  if (summary.latestQuota) {
    return {
      name: "Claude authentication / telemetry evidence",
      status: isStale(summary.latestQuota.capturedAt, ctx.now, ctx.freshnessMs) ? "STALE" : "PASS",
      detail: "status-line snapshot observed (credentials not inspected)"
    };
  }
  const lifecycle = ctx.events.some((event) => event.type === "prompt_lifecycle");
  if (lifecycle) {
    return {
      name: "Claude authentication / telemetry evidence",
      status: "WARN",
      detail: "hooks observed; no quota snapshot yet (credentials not inspected)"
    };
  }
  return {
    name: "Claude authentication / telemetry evidence",
    status: "UNAVAILABLE",
    detail: "no live Claude telemetry yet (credentials not inspected)"
  };
}
function hookIntegrationCheck(ctx) {
  if (ctx.pluginRoot && pluginHasNativeHooks(ctx.pluginRoot)) {
    return {
      name: "Hook integration",
      status: "PASS",
      detail: "plugin UserPromptSubmit and Stop hooks"
    };
  }
  const settingsPath = import_node_path9.default.join(resolveClaudeConfigDir(ctx), "settings.json");
  const loaded = readSettingsFile(settingsPath);
  if (!loaded.ok) {
    return { name: "Hook integration", status: "FAIL", detail: loaded.error };
  }
  if (!loaded.existed) {
    return { name: "Hook integration", status: "WARN", detail: "not installed" };
  }
  const hooks = loaded.value.hooks ?? {};
  if (hasPromptGaugeHooks(hooks)) {
    return {
      name: "Hook integration",
      status: "PASS",
      detail: "UserPromptSubmit and Stop collectors installed"
    };
  }
  return { name: "Hook integration", status: "WARN", detail: "PromptGauge hooks not installed" };
}
function fiveHourTelemetryCheck(ctx) {
  return windowTelemetryCheck(ctx, "5-hour quota telemetry", (snap) => snap.fiveHour);
}
function sevenDayTelemetryCheck(ctx) {
  return windowTelemetryCheck(ctx, "7-day quota telemetry", (snap) => snap.sevenDay);
}
function windowTelemetryCheck(ctx, name, pick2) {
  const snap = summarizeSession(ctx.events).latestQuota;
  if (!snap) {
    return { name, status: "UNAVAILABLE", detail: "no snapshots" };
  }
  if (isStale(snap.capturedAt, ctx.now, ctx.freshnessMs)) {
    return { name, status: "STALE", detail: snap.capturedAt };
  }
  if (!pick2(snap)) {
    return { name, status: "UNAVAILABLE", detail: "field absent on latest snapshot" };
  }
  return { name, status: "PASS", detail: "Claude-reported window present" };
}
function promptLifecycleCheck(ctx) {
  const starts = ctx.events.filter(
    (event) => event.type === "prompt_lifecycle" && event.phase === "start"
  ).length;
  const stops = ctx.events.filter(
    (event) => event.type === "prompt_lifecycle" && (event.phase === "stop" || event.phase === "stop_failure")
  ).length;
  if (starts === 0 && stops === 0) {
    return {
      name: "Prompt lifecycle",
      status: "UNAVAILABLE",
      detail: "no UserPromptSubmit/Stop yet"
    };
  }
  if (starts > 0 && stops > 0) {
    return {
      name: "Prompt lifecycle",
      status: "PASS",
      detail: `${starts} start(s), ${stops} stop(s)`
    };
  }
  return {
    name: "Prompt lifecycle",
    status: "WARN",
    detail: `${starts} start(s), ${stops} stop(s)`
  };
}
function promptAttributionCheck(ctx) {
  const ids = completedPromptIds(ctx.events);
  if (ids.length === 0) {
    return { name: "Prompt attribution", status: "UNAVAILABLE", detail: "no completed prompts" };
  }
  const latestId = ids[ids.length - 1];
  if (!latestId) {
    return { name: "Prompt attribution", status: "UNAVAILABLE", detail: "no completed prompts" };
  }
  const attr = attributePrompt(ctx.events, latestId);
  if (attr.estimatedApiCostDelta || attr.quotaDeltaFiveHour || attr.quotaDeltaSevenDay) {
    return {
      name: "Prompt attribution",
      status: "PASS",
      detail: "at least one derived metric on latest completed prompt"
    };
  }
  return {
    name: "Prompt attribution",
    status: "WARN",
    detail: "completed prompt without a valid snapshot pair (UNAVAILABLE, not zero)"
  };
}
function costTelemetryCheck(ctx) {
  const summary = summarizeSession(ctx.events);
  if (summary.latestQuota?.estimatedApiCostUsd) {
    return {
      name: "Cost telemetry",
      status: "PASS",
      detail: `estimated API-equivalent $${summary.latestQuota.estimatedApiCostUsd.value.toFixed(5)}`
    };
  }
  return {
    name: "Cost telemetry",
    status: "UNAVAILABLE",
    detail: "cost.total_cost_usd not observed"
  };
}
function contextTelemetryCheck(ctx) {
  const summary = summarizeSession(ctx.events);
  if (summary.latestQuota?.contextWindow) {
    return {
      name: "Context token telemetry",
      status: "PASS",
      detail: "latest API response context stored"
    };
  }
  return {
    name: "Context token telemetry",
    status: "UNAVAILABLE",
    detail: "context_window not observed"
  };
}
function privacyCheck(ctx) {
  for (const event of ctx.events) {
    const forbidden = findForbiddenKeys(event);
    if (forbidden.length > 0 || eventLooksPrivate(event)) {
      return {
        name: "Privacy",
        status: "FAIL",
        detail: `prohibited field in local log: ${forbidden[0] ?? "pattern match"}`
      };
    }
  }
  return { name: "Privacy", status: "PASS", detail: "no prohibited fields stored" };
}
function statusDataCheck(ctx) {
  if (ctx.skippedCorruptLines > 0) {
    return {
      name: "Status data",
      status: "WARN",
      detail: `local log has ${ctx.skippedCorruptLines} corrupt line(s)`
    };
  }
  if (!ctx.eventsExist) {
    return { name: "Status data", status: "WARN", detail: "no local snapshots yet" };
  }
  return { name: "Status data", status: "PASS", detail: "local event log present" };
}
function storageCheck(ctx) {
  try {
    import_node_fs8.default.mkdirSync(ctx.dataDir, { recursive: true });
    return { name: "Local storage", status: "PASS", detail: ctx.dataDir };
  } catch {
    return { name: "Local storage", status: "FAIL", detail: `cannot create ${ctx.dataDir}` };
  }
}
function permissionsCheck(ctx) {
  const probe = import_node_path9.default.join(ctx.dataDir, ".write-probe");
  try {
    import_node_fs8.default.mkdirSync(ctx.dataDir, { recursive: true });
    import_node_fs8.default.writeFileSync(probe, "ok", "utf8");
    import_node_fs8.default.unlinkSync(probe);
    return { name: "Permissions", status: "PASS", detail: "data directory is writable" };
  } catch {
    return { name: "Permissions", status: "FAIL", detail: "data directory is not writable" };
  }
}
function statusLineCommand(settings) {
  const statusLine = settings.statusLine;
  if (typeof statusLine !== "object" || statusLine === null) {
    return "";
  }
  const command = statusLine.command;
  return typeof command === "string" ? command : "";
}

// src/claude/hooks/install.ts
var import_node_fs9 = __toESM(require("node:fs"), 1);
var import_node_path10 = __toESM(require("node:path"), 1);
function resolveHookCommand(io) {
  const node = io.nodeExecutable ?? process.execPath;
  const cli = io.cliEntry ?? defaultCliEntry2();
  return `${quoteShellArg(node)} ${quoteShellArg(cli)} collect ${HOOK_MARKER}`;
}
function defaultCliEntry2() {
  return resolveCliEntry();
}
function statePathFor2(dataDir) {
  return import_node_path10.default.join(dataDir, HOOKS_STATE_FILE_NAME);
}
function installHooks(io) {
  const settingsPath = settingsPathFor(io);
  const hookCommand = resolveHookCommand(io);
  const loaded = readSettingsFile(settingsPath);
  if (!loaded.ok) {
    return {
      ok: false,
      alreadyInstalled: false,
      settingsPath,
      wrapperCommand: hookCommand,
      preservedExisting: false,
      message: loaded.error
    };
  }
  const planned = planHooksInstall(loaded.value, hookCommand);
  if (planned.alreadyInstalled) {
    return {
      ok: true,
      alreadyInstalled: true,
      settingsPath,
      wrapperCommand: hookCommand,
      preservedExisting: planned.previousExisted,
      message: "PromptGauge hooks already installed."
    };
  }
  import_node_fs9.default.mkdirSync(import_node_path10.default.dirname(settingsPath), { recursive: true });
  let backupPath;
  if (loaded.existed) {
    backupPath = `${settingsPath}.promptgauge-hooks-backup`;
    copyFileAtomic(settingsPath, backupPath);
    copyFileAtomic(settingsPath, `${settingsPath}.promptgauge-hooks-backup-${Date.now()}`);
  }
  writeJsonAtomic(settingsPath, planned.nextSettings);
  const state = {
    version: 1,
    installedAt: (io.now ?? (() => /* @__PURE__ */ new Date()))().toISOString(),
    hookCommand,
    events: ["UserPromptSubmit", "Stop"],
    previousExisted: planned.previousExisted
  };
  writeJsonAtomic(statePathFor2(io.dataDir), state);
  return {
    ok: true,
    alreadyInstalled: false,
    settingsPath,
    backupPath,
    wrapperCommand: hookCommand,
    preservedExisting: planned.previousExisted,
    message: planned.previousExisted ? "Installed PromptGauge UserPromptSubmit and Stop hooks alongside existing hooks." : "Installed PromptGauge UserPromptSubmit and Stop hooks."
  };
}
function uninstallHooks(io) {
  const settingsPath = settingsPathFor(io);
  const hookCommand = resolveHookCommand(io);
  const loaded = readSettingsFile(settingsPath);
  if (!loaded.ok) {
    return {
      ok: false,
      alreadyInstalled: false,
      settingsPath,
      wrapperCommand: hookCommand,
      preservedExisting: false,
      message: loaded.error
    };
  }
  const planned = planHooksUninstall(loaded.value);
  if (!planned.restored) {
    return {
      ok: true,
      alreadyInstalled: false,
      settingsPath,
      wrapperCommand: hookCommand,
      preservedExisting: false,
      message: "PromptGauge hooks were not installed."
    };
  }
  writeJsonAtomic(settingsPath, planned.nextSettings);
  const stateFile = statePathFor2(io.dataDir);
  if (import_node_fs9.default.existsSync(stateFile)) {
    import_node_fs9.default.unlinkSync(stateFile);
  }
  return {
    ok: true,
    alreadyInstalled: false,
    settingsPath,
    wrapperCommand: hookCommand,
    preservedExisting: true,
    message: "Removed PromptGauge hooks. Other hook entries were left in place."
  };
}
function describeHooks(io) {
  const settingsPath = settingsPathFor(io);
  const loaded = readSettingsFile(settingsPath);
  const lines = ["PromptGauge hooks status", "", `Settings:  ${settingsPath}`];
  if (!loaded.ok) {
    lines.push(`JSON:      FAIL (${loaded.error})`);
    return `${lines.join("\n")}
`;
  }
  if (!loaded.existed) {
    lines.push("JSON:      no settings.json yet");
    lines.push("Hooks:     not installed");
    return `${lines.join("\n")}
`;
  }
  const hooks = loaded.value.hooks ?? {};
  const installed = hasPromptGaugeHooks(hooks);
  lines.push(`Hooks:     ${installed ? "installed (UserPromptSubmit, Stop)" : "not installed"}`);
  const foreign = countForeignHooks(hooks);
  lines.push(
    foreign > 0 ? `Preserved: ${foreign} non-PromptGauge hook handler(s)` : "Preserved: N/A (no other hook handlers)"
  );
  return `${lines.join("\n")}
`;
}
function countForeignHooks(hooks) {
  let count = 0;
  for (const groups of Object.values(hooks)) {
    for (const group of groups ?? []) {
      for (const handler of group.hooks ?? []) {
        if (!isPromptGaugeHookCommand(handler.command)) {
          count += 1;
        }
      }
    }
  }
  return count;
}

// src/cli/commands/setup.ts
function runSetup(ctx) {
  const status = installStatusLine(ctx.settingsIo);
  if (!status.ok) {
    return {
      ok: false,
      message: [
        "Could not finish PromptGauge setup.",
        "",
        "Status line  Could not update Claude Code settings.",
        "",
        status.message.includes("malformed") ? "The Claude settings file is not valid JSON. Fix it, then run /promptgauge:setup again." : status.message,
        ""
      ].join("\n")
    };
  }
  let hooksActive = Boolean(ctx.pluginRoot && pluginHasNativeHooks(ctx.pluginRoot));
  if (!hooksActive) {
    const hooks = installHooks(ctx.settingsIo);
    hooksActive = hooks.ok;
    if (!hooks.ok) {
      return {
        ok: false,
        message: [
          "Could not finish PromptGauge setup.",
          "",
          "Hooks        Could not update Claude Code settings.",
          "",
          hooks.message,
          ""
        ].join("\n")
      };
    }
  }
  const wrapper = describeStatusLine(ctx.settingsIo);
  const statusLineActive = /Wrapper:\s+installed/.test(wrapper);
  return {
    ok: true,
    message: [
      "PromptGauge is ready.",
      "",
      `Hooks        ${hooksActive ? "Active" : "Inactive"}`,
      `Status line  ${statusLineActive ? "Active" : "Inactive"}`,
      "Storage      Ready",
      "",
      "Use Claude Code normally.",
      ""
    ].join("\n")
  };
}
function runCleanup(ctx) {
  const status = uninstallStatusLine(ctx.settingsIo);
  if (!status.ok) {
    return { ok: false, message: `${status.message}
` };
  }
  const nativeHooks = Boolean(ctx.pluginRoot && pluginHasNativeHooks(ctx.pluginRoot));
  if (!nativeHooks) {
    const hooks = uninstallHooks(ctx.settingsIo);
    if (!hooks.ok) {
      return { ok: false, message: `${hooks.message}
` };
    }
  }
  return {
    ok: true,
    message: [
      "PromptGauge cleanup finished.",
      "",
      "Status line  Restored",
      nativeHooks ? "Hooks        Stay until you uninstall the plugin" : "Hooks        Removed from Claude settings",
      "History      Kept",
      ""
    ].join("\n")
  };
}
function formatSimpleDoctor(checks) {
  const plugin = pick(checks, "Plugin");
  const hooks = pick(checks, "Hook integration");
  const statusLine = pick(checks, "PromptGauge statusLine integration");
  const storage = pick(checks, "Local storage");
  const quota = [pick(checks, "5-hour quota telemetry"), pick(checks, "7-day quota telemetry")];
  const statusLineLabel = statusLine?.status === "PASS" ? "PASS" : statusLine?.status === "FAIL" ? "FAIL" : "NEEDS SETUP";
  const pluginLabel = plugin?.status === "PASS" ? "PASS" : "MISSING";
  const hooksLabel = hooks?.status === "PASS" ? "PASS" : "NEEDS SETUP";
  const storageLabel = storage?.status === "PASS" ? "PASS" : "FAIL";
  const dataLabel = quota.some((check) => check?.status === "PASS") ? "AVAILABLE" : "UNAVAILABLE";
  const lines = [
    "PromptGauge Doctor",
    "",
    `Plugin        ${pluginLabel}`,
    `Hooks         ${hooksLabel}`,
    `Status line   ${statusLineLabel}`,
    `Storage       ${storageLabel}`,
    `Claude data   ${dataLabel}`,
    ""
  ];
  if (statusLineLabel === "NEEDS SETUP" || hooksLabel === "NEEDS SETUP") {
    lines.push("Run:");
    lines.push("/promptgauge:setup");
    lines.push("");
  }
  return lines.join("\n");
}
function pick(checks, name) {
  return checks.find((check) => check.name === name);
}

// src/claude/statusline/wrapper.ts
var import_node_child_process2 = require("node:child_process");
function runStatusLineWrapper(raw, ctx) {
  let fallback = "";
  try {
    const collect = ctx.collect ?? collectFromStdin;
    fallback = collect(raw, ctx.eventsFile, ctx.now).stdout;
  } catch {
  }
  const state = readInstallState(ctx.dataDir);
  const command = forwardCommand(state?.previousStatusLine);
  if (!command) {
    return normalizeLine(fallback);
  }
  const forward = ctx.forward ?? defaultForward;
  try {
    const result = forward(command, raw);
    if (result.stdout.length > 0) {
      return normalizeLine(result.stdout);
    }
    return "";
  } catch {
    return "";
  }
}
function forwardCommand(previous) {
  const command = previous?.command;
  if (!command || isPromptGaugeWrapperCommand(command)) {
    return void 0;
  }
  return command;
}
function defaultForward(command, input) {
  const result = (0, import_node_child_process2.spawnSync)(command, {
    input,
    encoding: "utf8",
    timeout: 8e3,
    shell: true,
    windowsHide: true
  });
  return {
    ok: result.status === 0,
    stdout: firstLine(result.stdout ?? ""),
    stderr: result.stderr ?? ""
  };
}
function firstLine(text) {
  return text.split(/\r?\n/)[0] ?? "";
}
function normalizeLine(text) {
  if (text.length === 0) {
    return "";
  }
  return text.endsWith("\n") ? text : `${text}
`;
}

// src/cli/program.ts
async function runCli(argv, io) {
  const parsed = parseArgs(argv);
  if (parsed.help) {
    io.stdout.write(helpText());
    return 0;
  }
  if (parsed.version) {
    io.stdout.write(`${VERSION}
`);
    return 0;
  }
  const dataDir = parsed.dataDir ?? resolveDataDir(io.env, io.home);
  const paths = resolvePaths(dataDir);
  ensureDataDir(dataDir);
  writeDefaultConfig(dataDir);
  const loaded = loadConfig(dataDir);
  const now = parsed.now ? new Date(parsed.now) : io.now();
  const home = io.home ?? defaultHome(io.env);
  switch (parsed.command) {
    case "status": {
      const { events } = readEvents(paths.eventsFile);
      io.stdout.write(renderStatus(events, loaded.config, now, parsed.simple));
      return 0;
    }
    case "doctor": {
      const { events, skippedCorruptLines } = readEvents(paths.eventsFile);
      const pluginRoot = detectPluginRoot(io.env, io.cliEntry);
      const checks = runDoctor({
        nodeVersion: io.nodeVersion ?? process.version,
        dataDir,
        eventsExist: events.length > 0,
        skippedCorruptLines,
        home,
        env: io.env,
        events,
        now,
        freshnessMs: loaded.config.freshnessMs,
        pluginRoot,
        claudeVersionCommand: parsed.claudeMissing ? () => ({ ok: false }) : io.env.PROMPTGAUGE_FAKE_CLAUDE === "1" ? () => ({ ok: true, version: "claude fake 0.0.0" }) : void 0
      });
      io.stdout.write(parsed.simple ? formatSimpleDoctor(checks) : formatDoctor(checks));
      return checks.some((check) => check.status === "FAIL") ? 1 : 0;
    }
    case "setup": {
      const pluginRoot = detectPluginRoot(io.env, io.cliEntry);
      const result = runSetup({
        pluginRoot,
        settingsIo: {
          home,
          dataDir,
          env: io.env,
          now: () => now,
          cliEntry: io.cliEntry,
          nodeExecutable: process.execPath
        }
      });
      io.stdout.write(result.message);
      return result.ok ? 0 : 1;
    }
    case "uninstall": {
      const pluginRoot = detectPluginRoot(io.env, io.cliEntry);
      const result = runCleanup({
        pluginRoot,
        settingsIo: {
          home,
          dataDir,
          env: io.env,
          now: () => now,
          cliEntry: io.cliEntry,
          nodeExecutable: process.execPath
        }
      });
      io.stdout.write(result.message);
      return result.ok ? 0 : 1;
    }
    case "collect": {
      const raw = io.readStdin ? await io.readStdin() : await readAll(io.stdin);
      const { stdout } = collectFromStdin(raw, paths.eventsFile, now);
      if (stdout) {
        io.stdout.write(stdout);
      }
      return 0;
    }
    case "install":
    case "statusline": {
      return runStatuslineCommand(parsed, io, dataDir, home, paths.eventsFile, now);
    }
    case "hooks": {
      return runHooksCommand(parsed, io, dataDir, home);
    }
    case "prompts": {
      const { events } = readEvents(paths.eventsFile);
      io.stdout.write(formatPrompts(events, parsed.limit ?? 10));
      return 0;
    }
    case "config": {
      io.stdout.write(`${JSON.stringify(loaded.config, null, 2)}
`);
      if (loaded.warnings.length > 0) {
        io.stderr.write(`${loaded.warnings.join("\n")}
`);
      }
      return 0;
    }
    case "report": {
      const { events } = readEvents(paths.eventsFile);
      io.stdout.write(renderStatus(events, loaded.config, now));
      io.stdout.write("\nNote: this is a local observation dump, not a billing statement.\n");
      return 0;
    }
    case void 0:
      io.stderr.write(`Unknown command. Try ${DISPLAY_NAME.toLowerCase()} --help
`);
      return 1;
    default:
      io.stderr.write(`Unknown command: ${parsed.command}
`);
      return 1;
  }
}
async function runStatuslineCommand(parsed, io, dataDir, home, eventsFile, now) {
  const sub = parsed.command === "install" ? "install" : parsed.subcommand;
  const settingsIo = {
    home,
    dataDir,
    env: io.env,
    now: () => now,
    cliEntry: io.cliEntry,
    nodeExecutable: process.execPath
  };
  if (sub === "install") {
    const result = installStatusLine(settingsIo);
    io.stdout.write(`${result.message}
`);
    return result.ok ? 0 : 1;
  }
  if (sub === "uninstall") {
    const result = uninstallStatusLine(settingsIo);
    io.stdout.write(`${result.message}
`);
    return result.ok ? 0 : 1;
  }
  if (sub === "status" || sub === void 0) {
    io.stdout.write(describeStatusLine(settingsIo));
    return 0;
  }
  if (sub === "run") {
    const raw = io.readStdin ? await io.readStdin() : await readAll(io.stdin);
    io.stdout.write(runStatusLineWrapper(raw, { eventsFile, dataDir, now }));
    return 0;
  }
  io.stderr.write("Usage: promptgauge statusline <install|uninstall|status>\n");
  return 1;
}
async function runHooksCommand(parsed, io, dataDir, home) {
  const settingsIo = {
    home,
    dataDir,
    env: io.env,
    now: io.now,
    cliEntry: io.cliEntry,
    nodeExecutable: process.execPath
  };
  if (parsed.subcommand === "install") {
    const result = installHooks(settingsIo);
    io.stdout.write(`${result.message}
`);
    return result.ok ? 0 : 1;
  }
  if (parsed.subcommand === "uninstall") {
    const result = uninstallHooks(settingsIo);
    io.stdout.write(`${result.message}
`);
    return result.ok ? 0 : 1;
  }
  if (parsed.subcommand === "status" || parsed.subcommand === void 0) {
    io.stdout.write(describeHooks(settingsIo));
    return 0;
  }
  io.stderr.write("Usage: promptgauge hooks <install|uninstall|status>\n");
  return 1;
}
function parseArgs(argv) {
  const parsed = { help: false, version: false, claudeMissing: false, simple: false };
  const rest = [];
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--help" || arg === "-h") {
      parsed.help = true;
    } else if (arg === "--version" || arg === "-v") {
      parsed.version = true;
    } else if (arg === "--data-dir") {
      parsed.dataDir = argv[i + 1];
      i += 1;
    } else if (arg === "--now") {
      parsed.now = argv[i + 1];
      i += 1;
    } else if (arg === "--limit") {
      parsed.limit = Number.parseInt(argv[i + 1] ?? "", 10);
      i += 1;
    } else if (arg === "--simple") {
      parsed.simple = true;
    } else if (arg === "--simulate-missing-claude") {
      parsed.claudeMissing = true;
    } else if (arg === "--pg-wrapper" || arg === "--pg-hook") {
      continue;
    } else if (arg?.startsWith("-")) {
      parsed.help = true;
    } else if (arg) {
      rest.push(arg);
    }
  }
  parsed.command = rest[0];
  parsed.subcommand = rest[1];
  if (!parsed.command && !parsed.version) {
    parsed.help = true;
  }
  return parsed;
}
function helpText() {
  return `${DISPLAY_NAME} ${VERSION}

See where your Claude Code usage goes.

\u{1F6A7} Early development / pre-release

Usage:
  promptgauge setup
  promptgauge status [--simple]
  promptgauge doctor [--simple]
  promptgauge uninstall
  promptgauge prompts [--limit 10]
  promptgauge statusline install
  promptgauge statusline uninstall
  promptgauge statusline status
  promptgauge hooks install
  promptgauge hooks uninstall
  promptgauge hooks status
  promptgauge collect
  promptgauge config
  promptgauge report
  promptgauge --help
  promptgauge --version

Commands:
  setup              One-time Claude Code status-line setup
  status             Show observed quota snapshots and prompt counts
  doctor             Check local integration health (no credentials inspected)
  uninstall          Restore previous statusLine; keep local history
  prompts            Recent completed prompts without prompt text
  statusline install Non-destructive Claude Code status-line wrapper
  statusline uninstall Restore the previous statusLine where possible
  statusline status  Explain what is installed
  hooks install      Add UserPromptSubmit and Stop collectors without replacing other hooks
  hooks uninstall    Remove only PromptGauge hook handlers
  hooks status       Explain which hooks are installed
  collect            Ingest Claude Code status-line or hook JSON from stdin
  config             Print the local configuration
  report             Print a local observation dump

Options:
  --data-dir <path>  Override local data directory
  --now <iso>        Evaluate time-dependent output at a fixed instant
  --limit <n>        Number of prompts to show (default 10)
  --simple           Compact status and doctor output
  -h, --help         Show this help
  -v, --version      Show version

PromptGauge is an independent open-source project and is not affiliated with Anthropic.
Quota fields are shown when Claude Code exposes them.
`;
}
function readAll(stream) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    stream.on("data", (chunk) => {
      chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(String(chunk)));
    });
    stream.on("end", () => {
      resolve(Buffer.concat(chunks).toString("utf8"));
    });
    stream.on("error", reject);
  });
}
function defaultHome(env) {
  return env.USERPROFILE ?? env.HOME ?? ".";
}

// src/index.ts
void main();
async function main() {
  const code = await runCli(process.argv.slice(2), {
    stdin: process.stdin,
    stdout: process.stdout,
    stderr: process.stderr,
    env: process.env,
    now: () => /* @__PURE__ */ new Date(),
    cliEntry: resolveCliEntry()
  });
  process.exit(code);
}
